### ISSUE TITLE
Support --max-warnings CLI flag

### ISSUE THREAD

**Issue by seriallos** [adametry/gulp-eslint#100]
`--max-warnings` is a pretty decent (if simplistic) method to bring linting to an existing codebase.  The idea is to drop in all the rules you want to support as warnings, determine the number of existing problems, and then set that number as the high water mark.  This gives one way of failing the lint run on new changes without requiring fixing every problem before getting linting into place.

As far as I've been able to tell, there's no way to use this CLI flag in gulp-eslint at this time.  It would be pretty awesome to hand this configuration into the lint task so that a warning count above the high water mark can fail pre-commit hooks or builds.

**Comment by adametry** [comment]
I agree. Have you come across the [gulp-eslint-threshold](https://github.com/krmbkt/gulp-eslint-threshold) package? It works *almost* like your PR. Here's an example that closes the gap:
```javascript
var gulp = require('gulp');
var eslint = require('gulp-eslint');
var threshold = require('gulp-eslint-threshold');
var PluginError = require('gulp-util').PluginError;

gulp.task('max-warn', function () {
	var maxWarnings = 2;
	var stream = gulp.src('src/**/*.js')
		.pipe(eslint())
		.pipe(threshold.afterWarnings(maxWarnings, function (warningCount) {
			stream.emit('error', new PluginError(
				'gulp-eslint',
				{
					name: 'ESLintMaxWarn',
					message: 'Failed because of too many warnings. ' +
							'Found ' + warningCount + (warningCount === 1 ? ' warning' : ' warnings') +
							', threshold is ' + maxWarnings + '.'
				}
			));
		}));
	return stream;
});
```

Unfortunately, it stops short of handling errors, providing access to the stream, or having a default handler that fails the stream. Perhaps, I'll send a PR that way...

Thoughts?

**Comment by adametry** [comment]
#101

**Comment by heylookltsme** [comment]
Bump. I would love this functionality in my project. :+1:

**Comment by heylookltsme** [comment]
Ah I just read through the [workaround here|https://github.com/adametry/gulp-eslint/pull/101#issuecomment-155612915]. 

That totally works and it's what I'll do, but I agree with @seriallos that built in support for the command line argument `--max-warnings` would be the simplest and most consistent with eslint's behavior, while admittedly not as flexible as the approach you took @adametry.

**Comment by shinnn** [comment]
Closing this as you can use autofixing feature if you need to lint a lot of unfixed files.
