### ISSUE TITLE
on-error callback

### ISSUE THREAD

**Issue by builtbylane** [adametry/gulp-eslint#102]
how would I create an on-error callback? I'd like to pass the stream to gulp-notify?

**Comment by thomasklein** [comment]
+1

**Comment by hownowbrowncow** [comment]
```
.pipe(eslint.failOnError().on('error', errorHandler))
```
That will give you an error message like:

```
name: 'ESLintError',
message: '"something" is defined but never used',
fileName: '/src/test.js',
lineNumber: 5,
```

You can do the same for `.failAfterError` but the error message is less specific

```
name: 'ESLintError',
message: 'Failed with 1 error',
```

Hope that helps!

**Comment by shinnn** [comment]
https://github.com/adametry/gulp-eslint/pull/104#issuecomment-148751662
