### ISSUE TITLE
gulp-eslint reports nothing if a glob is unsatisfied

### ISSUE THREAD

**Issue by johnnyreilly** [adametry/gulp-eslint#103]
Hi,

First of all, thanks for gulp-eslint - it's great!

I just encountered an issue as I was setting up a new project.  I had this:

```
var lintSrcs = ['./gulp/**/*.js', './src/**/*.js', './test/**/*.js'];

gulp.task('lint', function () {
  return gulp.src(lintSrcs)
    .pipe(eslint())
    .pipe(eslint.format());
});
```

And realised my lint task was producing nothing.  This was because there were no matches for tests.  So when I tweaked the srcs like so:

```
var lintSrcs = ['./gulp/**/*.js', './src/**/*.js']; // - tests now excluded
```

I started getting lint errors reported.  I guess this is a bug?

**Comment by shinnn** [comment]
@johnnyreilly Could you create a small repository by which we can reproduce the problem?

**Comment by adametry** [comment]
Is this still an issue?

**Comment by johnnyreilly** [comment]
I believe so but I haven't had time to provide a demo repo

**Comment by shinnn** [comment]
Feel free to comment more when you encounter the same issue.
