### ISSUE TITLE
jsx linting Unexpected token < 

### ISSUE THREAD

**Issue by Olgagr** [adametry/gulp-eslint#105]
I have a problem with linting jsx files with gulp-eslint. In my .eslintrc file I have settings:

```
"ecmaFeatures": {
        "jsx": true,
        "experimentalObjectRestSpread": true
    },
    "plugins": [
        "react"
    ]
```

I have also eslint-plugin-react installed. However, when I do (I'm using gulp-load-plugins):

```
.pipe($.eslint())
.pipe($.eslint.format())
.pipe($.eslint.failOnError());
```

I get error in main.js file:

```
var React = require('react');

var Main = React.createClass({

  displayName: 'Main',

  render: function() {
    return (
      <div>
        test
      </div>
    );
  }

});

module.exports = Main;
```
```
Unexpected token < at client/app/main.js
```
I don't see any other option I should setup to make it work. When I do linting through console:

```
eslint src/client/app/main.js
```

there is no error.

I'm using eslint 1.6.0 and gulp-eslint 1.0.0

**Comment by szymonkaliski** [comment]
Hey @Olgagr I stumbled upon the same problem, did you manage to fix it somehow?
