### ISSUE TITLE
Parsing error: Illegal import declaration

### ISSUE THREAD

**Issue by benrlodge** [adametry/gulp-eslint#106]
I'm getting the error `Parsing error: Illegal import declaration`

I'm using ES6 imports. 

When I first run lint, or run it manually I don't get the error, it's only when I save and it's run with my watch task. I was using 0.15 when I first got the error, upgraded to 1.0 and still get it.

This seems to maybe be related to https://github.com/eslint/eslint/issues/2112 and https://github.com/adametry/gulp-eslint/issues/39, but none are helping my issue.

I'm not sure where the error comes from as I haven't changed my `eslintrc` or babel setup since I first started my project a few months ago. So I'm guessing there is some dependency change causing this issue? 

Any ideas how to fix?

```
[09:07:46] ESLintError in plugin 'gulp-eslint'
Message:
    Parsing error: Illegal import declaration
```

lintrc:
```
{
  "ecmaFeatures": {
    "arrowFunctions": true,
    "blockBindings": true,
    "classes": true,
    "destructuring": true,
    "modules": true,
    "objectLiteralComputedProperties": true,
    "objectLiteralShorthandMethods": true,
    "objectLiteralShorthandProperties": true,
    "templateStrings": true,
    "jsx": true
  },
  "env": {
    "browser": true,
    "node": true,
    "jasmine": true
  },
  "plugins": [
    "react"
  ],
  "rules": {
    "camelcase": 0,
    "no-alert": 0,
    "no-else-return": 1,
    "strict": [2, "global"],
    "brace-style": [2, "stroustrup"],
    "comma-style": [1, "last"],
    "no-lonely-if": 1,
    "no-multi-spaces": 0,
    "no-mixed-requires": 2,
    "no-underscore-dangle": 0,
    "no-var": 2,
    "no-duplicate-case": 0,
    "no-func-assign": 0,
    "quotes": [1, "single", "avoid-escape"],
    "space-before-function-paren": [1, "never"],
    "space-after-keywords": [1, "always"],
    "space-before-blocks": [1, "always"],
    "space-in-brackets": 0,
    "space-in-parens": 0,
    "spaced-comment": 0,
    "new-cap": 0,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 1,
    "new-parens": 0,
    "no-use-before-define": 0,
    "no-shadow": 0
  },
  "globals": {
    "__BROWSER__": false,
    "__SERVER__": false,
    "__DEV__": false,
    "__PROD__": false,
    "__": false,
    "Promise": true,
    "casper": false,
    "jest": false
  }
}
```

My package.json includes:
```
    "babel-core": "^4.7.0",
    "babel-eslint": "^4.1.3",
    "gulp-eslint": "^1.0.0",
```

My lint and watch tasks:
```
// var $ = require('gulp-load-plugins')();
gulp.task('lint', function () {
  return gulp.src(['./app/scripts/**/*.{js, jsx}'])
    .pipe($.eslint())
    .pipe($.eslint.format())
    .pipe($.eslint.failOnError());
});

gulp.task('watch', function() {
  gulp.watch(app + 'images/**/*.{png,jpg,jpeg,gif,svg}', ['images']);
  gulp.watch(app + 'stylus/**/*.styl', ['styles']);
  gulp.watch(app + 'index.mustache', ['html']);
  gulp.watch(app + 'scripts/**/*.jsx', ['scripts', 'lint']);
  gulp.watch(app + 'scripts/**/*.js', ['scripts', 'lint']);
});
```

**Comment by adametry** [comment]
Unfortunately, I haven't been able to reproduce this issue. So, here are some wild guesses:
1. *Syntax error:* Is the `import` nested? If `import` is not at the top level of a module, the `espree` parser produces the error your seeing.
2. *Wrong parser:* I see you have espree's `"ecmaFeatures":{"modules":true}` option, but are you trying to use `babel-eslint`? If so, [set the parser](http://eslint.org/docs/user-guide/configuring#specifying-parser) with `"parser":"babel-eslint"`. The `babel-eslint` parser may provide a more helpful error message.
3. *Stale node_modules:* Try deleting your node_modules directory and reinstalling your package dependencies. 
4. *Unexpected `app` value:* Ensure that `app + 'scripts/**/*.js'` produces the expected path.

If none of the above resolve the issue, provide a gist or repo that demonstrates the issue so I can get an exact copy. 

On another note: you may want to switch to using `failAfterError` so you can see the lint report before the the "lint" task fails.

**Comment by benrlodge** [comment]
Thanks for the reply @adametry - it seems like one of your suggestions may have fixed the issue - I made a handful of changes and some of your suggestions above, and it seems to be working now.

Thanks

**Comment by Xurma2** [comment]
@benrlodge what you do?

**Comment by seoyoochan** [comment]
@Xurma2 @benrlodge  *Wrong parser* was the problem. `"parser": "babel-eslint"` did fix the problem.
