### ISSUE TITLE
gulp-eslint does not work with .eslintignore

### ISSUE THREAD

**Issue by golyshevd** [adametry/gulp-eslint#11]
please, set fixed eslint version in package.json or support exclusions correctly (eslint 0.7.4)

**Comment by adametry** [comment]
I worked on this a bit more and believe it's picking up .eslintignore and evaluates the file path relative to the .eslingignore file. So, it shouldn't require the "**/" prefix anymore. Let me know if I missed anything.

**Comment by adametry** [comment]
I'm going to close this issue since there is a published solution. I can reopen it if more work is needed.

**Comment by steida** [comment]
There is probably wrong precedence resolution. `eslint` worked well, but `gulp eslint` didn't ignored directory. The reason was, I had an empty .eslintignore file in ignored directory, which somehow disabled ignoration of root .eslintignore. It's small bug anyway.
