### ISSUE TITLE
Support 'extends' in options

### ISSUE THREAD

**Issue by jonrimmer** [adametry/gulp-eslint#113]
If I include an ```extends``` field in the options, it seems to be ignored?

```js
gulp.src('**/*.js')
  .pipe(eslint({
    extends: 'eslint:recommended'
  });
```

**Comment by adametry** [comment]
There's a release candidate that does just that. It will be published to the "latest" tag this week.

Until then:
```shell
npm install gulp-eslint@rc
```

**Comment by adametry** [comment]
btw, if you'd prefer not to use the "rc" version. You can use "extends" the current `gulp-eslint` by moving it to the "baseConfig" property, like so:
```javascript
gulp.src('**/*.js')
  .pipe(eslint({
    baseConfig:{
      extends: 'eslint:recommended'
    }
  });
```
The "rc" simply migrates the property automatically.

**Comment by jonrimmer** [comment]
Thanks! :+1:
