### ISSUE TITLE
Does not work with projects with more than 16 files large.

### ISSUE THREAD

**Issue by whroman** [adametry/gulp-eslint#114]
### Issue
`stream` is currently being instantiated without the `highWaterMark` option. When this occurs, the stream is instantiated with a default `highWaterMark` value of 16 ([according to the V4.2.1 `stream` docs](https://nodejs.org/api/stream.html#stream_new_stream_readable_options)). This means that this plugin cannot accept more than 16 files.

### Fix
I was able to resolve this locally by making a change in the following declaration:

[Line 22 of `util.js`] (https://github.com/adametry/gulp-eslint/blob/master/util.js#L22)

    var stream = new TransformStream({
        highWaterMark: 50    // This is the line that I added
        objectMode: true
    });

[The only relevant change that I see in the Node Changelog in regards to `stream`'s `highWaterMark` option](https://github.com/nodejs/node/blob/master/CHANGELOG.md#20130821-version-0117-unstable) occurred ages ago on August 21, 2013.

### Implementation
I would submit a PR, but I'm unsure of how the project owner would like to approach this. A `highWaterMark` plugin-level option? Lock-in an absurdly high `highWaterMark`?

### Environment Details
Node `0.12.7` through `4.2.1`
gulp-eslint `1.0.0`
eslint `1.7.3`

**Comment by adametry** [comment]
Take a moment to read issue #36, specifically [this comment](https://github.com/adametry/gulp-eslint/issues/36#issuecomment-109324959). 16 files is fine, until the last stream in the pipeline has nowhere to drain. Be sure the end of the stream either returns in the gulp task, terminates with a writable stream, or has a "data" event listener (allowing a readable to clear its highWaterMark-limited buffer).

**Comment by whroman** [comment]
Gah, I had't managed to find that issue. Sorry for creating noise.
