### ISSUE TITLE
Support for "argsIgnorePattern"

### ISSUE THREAD

**Issue by hackerrdave** [adametry/gulp-eslint#115]
Hi, my team is using this plugin and we ran into an issue where the rule we set for ignoring unused arguments prepended with an underscore was not taking effect. Here is our .eslintrc setup:

    "rules": {
        "no-console": 0,
        "indent": [
            2,
            4,
            {
                "SwitchCase": 1
            }
        ],
        "quotes": [
            2,
            "single",
            "avoid-escape"
        ],
        "linebreak-style": [
            2,
            "unix"
        ],
        "semi": [
            2,
            "always"
        ],
        "curly": [
            2
        ],
        "no-unused-vars": [
            2,
            {
                "args": "all",
                "argsIgnorePattern": "^_"
            }
        ]
    },

The latest version of eslint (1.7.3) seems to work with this plugin, and correctly reads the rule for `argsIgnorePattern`. Is there a reason why we can't upgrade to the latest eslint?

Thanks!

**Comment by adametry** [comment]
The current version of gulp-eslint depends on eslint@^1.0.0 ([1.0.0 <= v < 2.0.0](https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4)), which should install eslint 1.7.3.

From your project(.json) root, run `npm ls eslint` to print the location and version of any eslint packages installed in your project. You *should* see something to the tune of:
```shell
└─┬ gulp-eslint@1.0.0
  └── eslint@1.7.3
```
If there's an older version of eslint installed within gulp-eslint, run `npm update --depth 2`. If there's a version of eslint installed beside/peer gulp-eslint, you'll have to update that version or remove it and reinstall/update gulp-eslint.

**Comment by hackerrdave** [comment]
For some reason it was installing the older version of eslint (1.0.0) previously, and running `npm update` fixed that, thanks for the help!!
