### ISSUE TITLE
Support for eslint 1.10.3

### ISSUE THREAD

**Issue by musbaig** [adametry/gulp-eslint#123]

**Comment by adametry** [comment]
ESLint 1.10.3 is already supported. You may need to update your local node_modules by reinstalling or using `npm update --depth 2`. If you are having an issue with the version, please provide details.

**Comment by musbaig** [comment]
Yup, you nailed it, node_modules wasn't updating properly, needed the `--depth 2` parameter, my bad. Thanks for the tip!!
