### ISSUE TITLE
Sourcemap weirdness

### ISSUE THREAD

**Issue by jwalton** [adametry/gulp-eslint#127]
If I do this:

```
    gulp.src(['src/**/*.coffee'])
    .pipe(sourcemaps.init())
    .pipe coffee()
    .pipe(sourcemaps.write())
    .pipe(eslint({...}))
    .pipe(eslint.format(require('eslint-path-formatter')))
    .pipe(eslint.failAfterError())
```

Then I get line numbers in eslint-path-formatter from the compiled JS file.  But if I do this:

```
    gulp.src(['src/**/*.coffee'])
    .pipe(sourcemaps.init())
    .pipe coffee()
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('lib')) // <--------- Added this line!
    .pipe(eslint({...}))
    .pipe(eslint.format(require('eslint-path-formatter')))
    .pipe(eslint.failAfterError())
```

Then eslint-path-formatter uses the sourcemaps and generates line numbers from the coffee files.  O_o  The sourcemaps are inline, so they should be there either way (I even wrote a little dummy transform to spit out the file contents to make sure they were identical in both cases).  Any idea what's going on here?

**Comment by jwalton** [comment]
If I add this in place of the `.pipe(gulp.dest('lib'))`:

```
.pipe((function() {
  var answer = new stream.Transform({objectMode: true});
  answer._transform = function(file, encoding, callback) {
    file.history.push('/Users/jwalton/benbria/loop/foo/statisticsService.js');
    return callback(null, file);
  };
  return answer;
})())
```

This fixes it too.  That's even weirder.  :P

**Comment by jwalton** [comment]
Oh, no, the file.history hack only works if the file actually exists on the disk.  I'm guessing eslint-path-formatter is trying to read the file off the disk?

**Comment by shinnn** [comment]
Should be reported on https://github.com/Bartvds/eslint-path-formatter/issues.
