### ISSUE TITLE
gulp-eslint@2.0.0-rc-2 do not supports javascript decorators

### ISSUE THREAD

**Issue by dexteryy** [adametry/gulp-eslint#130]
Gulp results:
```
Error: ./js/temp/entry.js
Module build failed: SyntaxError: staticweb/js/temp/entry.js: Unexpected token (175:2)
  173 | class Person {
  174 |
> 175 |   @nonenumerable
      |   ^
  176 |   get kidCount() {
  177 |     return this.children.length;
  178 |   }
    at Parser.pp.raise (staticweb/node_modules/babylon/index.js:1413:13)
```

package.json:
```javascript
  "devDependencies": {
    "babel-eslint": "^4.1.6",
    "eslint": "^2.0.0-beta.1",
    "eslint-plugin-react": "^3.15.0",
    "gulp": "^3.9.0",
    "gulp-eslint": "^2.0.0-rc-2",
```

.eslintrc:
```javascript
{
  "parser": "babel-eslint",
  "plugins": [
    "react",
  ],
  "parserOptions": {
    "ecmaVersion": 6,
    "ecmaFeatures": {
      "jsx": true,
    },
    "sourceType": "module",
  },
  "rules": {
    "strict":                      0,
```

The same configuration files are working well In Atom (atom-eslint)

**Comment by adametry** [comment]
This appears to be an environment issue. This setup works fine when I run it as described; however, there may be other details involved in your issue.

Do you have a .babelrc file? Are there any other .eslintrc files and where are they relative to *staticweb/js/temp/entry.js*? Are you passing a configuration to gulp-eslint? atom-eslint defaults to loading .eslintrc; however ESLint deprecated that file name in favor of [.eslintrc.*](http://eslint.org/docs/user-guide/configuring#configuration-file-formats). Do you have a .eslintrc.json or .eslintrc.yml file? Have you tried reinstalling your node_modules to make sure the packages are current?

Note: The error doesn't appear to be from eslint/gulp-eslint. It's using the babel parser (babylon), which leads me to believe it's picking up the .eslintrc correctly, but babel/babel-eslint is not configured to recognize decorators.

**Comment by dexteryy** [comment]
Thanks! It's indeed my problem. Everthing works fine after I reinstall node_modules, although I do reinstall them before I post this issue...-_-b
