### ISSUE TITLE
Update to latest eslint

### ISSUE THREAD

**Issue by gunta** [adametry/gulp-eslint#131]
Update to latest eslint version.

Thank you!

**Comment by adametry** [comment]
The latest version of ESLint (at this time, eslint@latest = 1.10.3) is already supported by gulp-eslint. Additionally, the gulp-eslint@rc uses the eslint@next tag (2.0.0-beta.1). 

If you have a local environment that has an older version of eslint, update (`npm update gulp-eslint --depth=2`) or reinstall your node_modules directory to get the latest version.
