### ISSUE TITLE
Error: Can not find module eslint-config-eslint:recommended coming when my config file contains "extends":"eslint:recommended"

### ISSUE THREAD

**Issue by sam1111** [adametry/gulp-eslint#137]
How do I load such a config file?

**Comment by adametry** [comment]
Are ESLint and gulp-eslint both installed in a local node_modules or are one/both of them installed globally?

**Comment by sam1111** [comment]
ESlint is installed globally while gulp-eslint is installed in local.

**Comment by sam1111** [comment]
Never mind! Using latest version of gulp-eslint fixes the issue.
