### ISSUE TITLE
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by jingzhou123** [adametry/gulp-eslint#139]
after I install eslint-plugin-react by `npm i eslint-plugin-react`, it works. 
my node version: 5.5

**Comment by danactive** [comment]
Are you using airbnb/base? See this issue https://github.com/airbnb/javascript/issues/751

**Comment by jingzhou123** [comment]
many thanks to you @danactive ! However, I'm not using `airbnb/base`; now, the plugin works by installing `eslint-plugin-react`. Maybe I miss something. Close this issue.

**Comment by ljharb** [comment]
See https://github.com/airbnb/javascript/pull/829
