### ISSUE TITLE
No output (if files to be linted is not in the same folder – or subfolder – as gulp)

### ISSUE THREAD

**Issue by kaptenw** [adametry/gulp-eslint#141]
Hi,

I've probably done a really basic mistake somewhere. But I've been trying `gulp-eslint` to output errors for the last 2 hours. Feel free to tell me to continue with my day job and to stop pursuing ever working with code of any form, but I'm lost. Any guidance is appreciated.

Cheers!

`gulpfile.js`
```
'use strict';

var gulp      = require('gulp'),
    config    = require('./config.json'),
    functions = require('./functions.js'),
    plugins   = require('gulp-load-plugins')();

gulp.task( 'js:lint', functions.getTask('js-eslint', gulp, config, plugins) );
```

`config.json`
```
{
    ...
    "esLint": {
        "rules": {
            "camelcase": 2,
            "curly": 2,
            "brace-style": [2, "1tbs"],
            "quotes": [2, "single"],
            "semi": [2, "always"],
            "space-in-brackets": [2, "never"],
            "space-infix-ops": 2
        }
    }
}

```

`gulp_task/js-lint.js`
```
module.exports = function( gulp, config, plugins, functions ) {
    'use strict';

    var source = [
            config.src.js + 'test.js'
        ];

    return function() {
        gulp.src( source )
        .pipe( plugins.eslint({
            config: config.esLint
        }))
        .pipe( plugins.eslint.format() )
        .pipe( plugins.eslint.failAfterError() )
        .pipe( functions.onSuccess(plugins, 'JS:lint', 'Lint finished running') );
    };
};
```

`test.js` – Snatched from http://eslint.org/docs/rules/camelcase
```
var my_favorite_color = "#112C85";

function do_something() {
    // ...
}

obj.do_something = function() {
    // ...
};

var obj = {
    my_pref: 1
};
```
`output`
```
WalkPro:gulp Walker$ gulp js:lint
[14:41:36] Using gulpfile ~/Sites/_tmp/gulp/test/gulpfile.js
[14:41:36] Starting 'js:lint'...
[14:41:36] Finished 'js:lint' after 251 ms
[14:41:36] gulp-notify: [Success JS:lint] Success: Lint finished running
```

**Comment by adametry** [comment]
In "js-lint.js" be sure to [return the stream](https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support).

**Comment by jayzawrotny** [comment]
I'm experiencing the same issue myself. No matter what I throw at it I get a false positive. Can you test running your source against the eslint executable itself? I've found that works fine but for some reason this gulp plugin raises no errors.

**Comment by adametry** [comment]
@jayzawrotny, [the](https://github.com/adametry/gulp-eslint/issues/136) [original](https://github.com/adametry/gulp-eslint/issues/134) [issue](https://github.com/adametry/gulp-eslint/issues/129) [comes](https://github.com/adametry/gulp-eslint/issues/93) [up](https://github.com/adametry/gulp-eslint/issues/36) [often](https://github.com/adametry/gulp-eslint/issues/30), and has nothing to do with the gulp-eslint plugin (see the [Gulp docs](https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support)). If you are experiencing another issue, please help me reproduce it in a separate issue thread.

**Comment by kaptenw** [comment]
Thanks for your reply regarding returning the stream, @adametry!

It works just fine when I return the stream and have the files I want to lint in the same (or in a subfolder) as my gulpfile. But it seems like it all boils down to that gulp-eslint doesn't like it when the files to be linted is located in a folder outside of the gulp folder.

Working example:
```
project
├── gulp
│   └── gulpfile.js
│   ├── lint-me.js
│   ├── scripts
│       ├── lint-me-too.js
```

*Not* working example:
```
project
├── gulp
│   └── gulpfile.js
├── scripts
│   └── lint-me.js
```

**Comment by polako** [comment]
@kaptenw Same problem here.

**Comment by jayzawrotny** [comment]
@adametry That is definitely not the issue. 

1. I am calling the done gulp task when when the ending writable stream emits a finish event
2. My setup works fine prior to 2.0. If I downgrade to say `1.1.1` it works as expected.
3. After testing the suggestion that I'm not returning the stream by changing the workflow to return the stream, I still get no output:

So I don't think it is unreasonable to suspect it has something to do with this reported issue.

## Suggested Source that still does not work

```js
gulp.task('lint', () => {
 return gulp.src('app/js/**/*.{js,jsx}')

    // Lint the file
    .pipe(eslint(config))

    // Output the results
    .pipe(eslint.formatEach());
});
```

## My Actual Source

```js
gulp.task('lint', (done) => {
  gulp.src('app/js/**/*.{js,jsx}')

    // Don't break on errors
    .pipe(plumber({ errorHandler: true }))

    // Lint the file
    .pipe(eslint(config))

    // Output the results
    .pipe(eslint.formatEach())
    
    // logEnd is a writable stream which also allows more than 16 files at once to be processed  
    .pipe(logEnd())

    // Event only emitted when 
    .on('finish', () => done());
});
```

**Comment by matthewrose** [comment]
Hey everyone, I believe the problem you speak of is related to this issue: https://github.com/eslint/eslint/issues/5314

For now, setting the option "dotfiles" to true should resolve the issue, but it's not an ideal fix I realize.

**Comment by IanVS** [comment]
ESLint has made a fix in our master branch.  It would be great if someone here could try it out and confirm it is now working.

**Comment by makky3939** [comment]
I tried v1.1.1. It working.
(This is a temporary way.)

**Comment by shinnn** [comment]
This issue id fixed. [*evidence*](https://github.com/adametry/gulp-eslint/issues/148#issuecomment-232443925)
