### ISSUE TITLE
format() with failAfterError() does not trigger errors

### ISSUE THREAD

**Issue by rstoenescu** [adametry/gulp-eslint#142]
Calling eslint.format() followed by eslint.failAfterError() does not trigger any errors.
Using latest gulp-eslint npm version at this time: 2.0.0

**Comment by adametry** [comment]
Are you [returning the stream](https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support) in your gulk task?

**Comment by rstoenescu** [comment]
It wasn't this, it was a quirk in my module. No bug with gulp-eslint. Sorry for wasting your time :(
The bug is invalid.

**Comment by adametry** [comment]
No problem. Good luck with your project.
