### ISSUE TITLE
Add support for --debug and --print-config

### ISSUE THREAD

**Issue by taji** [adametry/gulp-eslint#143]
I'm trying to troubleshoot my eslint configuration as specified using gulp-eslint and I need a baseline sanity check as to what rules are being loaded.  Checking the documentation, I'm not seeing support for these two useful parameters.

**Comment by dylancwood** [comment]
That's a little tricky to implement here. This plugin uses `gulp.CLIEngine`, which does not support either of the options that you mention. When you pass those options on the command line, they are actually fed into `gulp.cli`, which wraps `gulp.CLIEngine`, and provides `printConfig` functionality. 

We can borrow the `gulp.cli` implementation of `printConfig` and add it to this plugin. Here's an example. 
https://github.com/dylancwood/gulp-eslint/commit/bb819d2fb87761868e27d0d5bd99c516b309f34a

@adametry: Let me know what you think of this approach, and I can put together a PR with tests and documentation updates.

**Comment by shinnn** [comment]
> --debug

You can simulate `--debug` flag by setting `DEBUG` environment variable `"eslint:*,-eslint:code-path"`. https://github.com/eslint/eslint/blob/18fbc4b86ac9fb84fb370c68b9a60d9b70cafa66/bin/eslint.js#L21

> --print-config

Out of gulp-eslint scope.
