### ISSUE TITLE
.eslintrc not resolving to nearest parent

### ISSUE THREAD

**Issue by patbaker82** [adametry/gulp-eslint#15]
I'm finding that when .eslintrc's are defined for specific directories and there is also a root .eslintrc, gulp-eslint is utilizing the root level.  I confirmed this by manually running eslint to confirm it is correctly leveraging the nearest parent to the javascript file.

**Comment by adametry** [comment]
The latest update replicates the executeOnFiles config lookup while still using the vinyl file contents. Give it a shot and let me know if it's works for you.

**Comment by adametry** [comment]
I'll close this issue since a solution has been published. It can be reopened if it needs more work.

**Comment by lucasmciruzzi** [comment]
Working for me, thanks!
