### ISSUE TITLE
Support ESLInt Shareable Configs

### ISSUE THREAD

**Issue by noelmace** [adametry/gulp-eslint#152]
PROBLEM : Shareable Configs simply do not work with gulp-eslint when using configuration files. (using 2.0.0)

USE CASE :

In one of my projects, my lint task isn't showing all eslint errors, while eslint-cli was.

I'm using an eslint-config-noelmace npm dependency, and I assume that the problem could be from that.

Here is an example of configuration : 

gulp task configuration (config.paths.scripts is ok) :
``` javascript
export let lintGen = (params = false) => {
    let configuration = params || {};
    configuration.fix = true;
    return lazypipe()
        .pipe(eslint, configuration)
        .pipe(eslint.format)
        .pipe(eslint.failAfterError);
};

gulp.task('lint:scripts', 'Lint the application\'s JS files', () => {
    return gulp.src("app/!(libs)/**/*.js")
        .pipe(debug({
            title: 'test'
        }))
        .pipe(lintGen()());
});
```

.eslintrc
``` json
{
    "extends": "noelmace/angular-base"
}
```

package.json
``` json
{ "scripts" : { "lint": "eslint \"app/!(libs)/**/*.js\" || true" } }
```

For example, when I'm adding a double quote to my code, ``npm run lint`` is showing the following error, when ``gulp lint:scripts`` isn't :
``31:17  error  Strings must use singlequote``

**Comment by dwieeb** [comment]
This issue report is sort of all over the place, but accurate. [Shareable Configs](http://eslint.org/docs/developer-guide/shareable-configs) simply do not work with gulp-eslint when using configuration files.

**Comment by dwieeb** [comment]
In the meantime I am using gulp-shell like this:

```javascript
gulp.task('eslint', shell.task('eslint .'));
```

Works great 👍

**Comment by noelmace** [comment]
Yes @dwieeb, sorry, I edited the question to correct that ...

Indeed, the shell works great in Unix environments. But right now, I'm trying to minimise the number of OS dependencies (I'm building a dev environment for Windows 7 users) ...

Any idea where is the problem in gulp-eslint, and how we could correct this ?

**Comment by noelmace** [comment]
I'll look at util.migrateOptions, I think the problem could be here.

**Comment by shinnn** [comment]
I added a test to check if gulp-eslint supports `extends: '@your/sharable-config'` https://github.com/adametry/gulp-eslint/commit/b0c281652d058b6962ad9501dba484ff1ea85e1e, and the test passes. Perhaps this problem was fixed in https://github.com/adametry/gulp-eslint/commit/505779d1c8c4d989cb7104e7bbbc261ffaef7eee.

@noelmace @dwieeb Feel free to comment more if the problem seems to remain unresolved.

**Comment by noelmace** [comment]
This issue appeared indeed to have been fixed in one of my new projects. Thank you for your help.

**Comment by shinnn** [comment]
@noelmace No problem. Thanks for the issue report and confirmation.
