### ISSUE TITLE
Parser is not working anymore

### ISSUE THREAD

**Issue by perrin4869** [adametry/gulp-eslint#153]
Related to: https://github.com/babel/babel-eslint/issues/312

Since `eslint@2.10.0`, my linting [here](https://travis-ci.org/perrin4869/react-onenterkeydown/jobs/130315342) started failing. With `2.10.1`, simply running `eslint src/index.js` stopped giving me an error, but running it with `gulp-eslint` kept failing.

Edit: additional related issues: https://github.com/eslint/eslint/issues/6158 https://github.com/eslint/eslint/pull/6160

**Comment by perrin4869** [comment]
This seems to be the fix: https://github.com/eslint/eslint/pull/6183

**Comment by aikssen** [comment]
Eslint by itself works fine linting the code with this command `$ eslint --ext .jsx src/js/**/*.jsx`.
But executing the same test using gulp-eslint always throws  `error  Parsing error: Unexpected token =` .
The thing is that gulp-eslint is not taken the parser in .eslintrc `{"parser": "babel-eslint"}`.

I always get the error with the class properties (es7).
```
class LoginForm extends Component {
  static defaultProps = { 
   	....
  }
  handleOnClick = (e) => {
   	....
  }
}
```

**Comment by shinnn** [comment]
The latest version correctly choose a custom parser specified in a config file.

```
$ ls -1a
.eslintrc.js
fixture.js
gulpfile.js
node_modules/
package.json
```

`fixture.js`:

```js
module.exports = {
  parser: 'babel-eslint'
};
```

`fixture.js`:

```js
class Foo {
  bar = 1;
}
```

`gulpfile.js`:

```js
'use strict';
const gulp = require('gulp');
const eslint = require('gulp-eslint');

gulp.task('default', () => {
  return gulp.src('./fixture.js')
  .pipe(eslint())
  .pipe(eslint.format());
});
```

`package.json`:

```json
{
  "name": "test",
  "private": true,
  "devDependencies": {
    "babel-eslint": "^6.1.2",
    "gulp": "gulpjs/gulp#d8f5c90a0622d19ef1943a2a3d02dc50e3c853e7",
    "gulp-eslint": "^3.0.1"
  }
}
```

```
$ node --version
v6.3.0

$ npm --version
3.10.5

$ node node_modules/gulp/bin/gulp.js
[03:47:28] Using gulpfile ~/test/project/gulpfile.js
[03:47:28] Starting 'default'...
[03:47:28] Finished 'default' after 181 ms
```
