### ISSUE TITLE
Cannot read config file

### ISSUE THREAD

**Issue by hassankhan** [adametry/gulp-eslint#158]
Hi there,

Trying to use the package but it keeps saying it can't read the file when it definitely exists. Interestingly it doesn't matter whether I use a JS or a JSON file, and it definitely reads the file because if I make a change to it to make it invalid, the error changes.

```js
gulp.task('static', function () {
  return gulp.src('**/*.js')
    .pipe(excludeGitignore())
    .pipe(eslint({
        // Load a specific ESLint config
        config: '.eslintrc.js'
    }))
    .pipe(eslint.format())
    .pipe(eslint.failAfterError());
});
```

**Comment by shinnn** [comment]
`config` is not a valid gulp-eslint option. Read the document carefully.

**Comment by hassankhan** [comment]
Sorry, was hitting one problem after the next, brain clearly stopped working somewhere around this point!
