### ISSUE TITLE
Update to ESLint 0.10.0

### ISSUE THREAD

**Issue by MethodGrab** [adametry/gulp-eslint#16]
`0.10.0` has been [released](https://github.com/eslint/eslint/releases/tag/v0.10.0): http://eslint.org/blog/2014/11/eslint-0.10.0-released!
Please could you update the `eslint` dependency to use this version?

**Comment by slacktracer** [comment]
+1

**Comment by MethodGrab** [comment]
Closing this as it's now out of date, see #19.
