### ISSUE TITLE
Syntax error: Use of const in strict mode

### ISSUE THREAD

**Issue by limonte** [adametry/gulp-eslint#161]
It seems that v3.0 broken something:

https://travis-ci.org/limonte/sweetalert2/builds/141918923

![](https://i.imgur.com/Y3cwYQG.png)

**Comment by klimashkin** [comment]
You use 0.10 according to travis.
ESLint v3.0.0 now requires Node.js 4 or higher.
http://eslint.org/blog/2016/07/eslint-v3.0.0-released

**Comment by limonte** [comment]
That's it! Thanks for the support!

**Comment by Lavinia-Dan** [comment]
I need some help too about this problem.
Node v4.5.0
ESlint v3.0.1
![2016-11-04_1604](https://cloud.githubusercontent.com/assets/5837544/20008282/9d409c20-a2a8-11e6-8bbd-2941a617ff99.png)
What am I missing to get this to work? It works on most my teammates machines, except for a couple of us and we haven't figured out yet why or what the differences might be, we have the same packages. 
For some it is working with a version below v4.5.0, while for another teammate that uses node v6.9.1 is not working.
