### ISSUE TITLE
error reported on template string

### ISSUE THREAD

**Issue by liushuping** [adametry/gulp-eslint#162]
gulp-eslint reports error on template string
```
Unexpected character '`'
```

**Comment by klimashkin** [comment]
What Nodejs version do you use?
ESLint v3.0.0 now requires Node.js 4 or higher.
http://eslint.org/blog/2016/07/eslint-v3.0.0-released

**Comment by liushuping** [comment]
````
node -v
v4.2.1
```

**Comment by shinnn** [comment]
http://www.catb.org/esr/faqs/smart-questions.html#forum
