### ISSUE TITLE
Undocumented peer dependency on eslint-config-defaults

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [adametry/gulp-eslint#163]
See https://github.com/adametry/gulp-eslint/issues/139.

After installing onto a clean new project, running `gulp eslint` with the following task would give errors like `Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'`. After installing the react plugin, similar errors came up.

```javascript
gulp.task("eslint", () => {
    return gulp.src(["*.js", "test/**/*.js"])
        .pipe(eslint())
        .pipe(eslint.format())
        .pipe(eslint.failAfterError());
});
```

**Comment by shinnn** [comment]
Why did you report it on *this* repository instead of ESLint or ESLint configs you're using?

**Comment by shinnn** [comment]
No feedback.
