### ISSUE TITLE
Add support for .eslintrc.json

### ISSUE THREAD

**Issue by talha-asad** [adametry/gulp-eslint#164]
I see that a `.eslintrc` file is supported however the JSON variant of it is not supported.

**Comment by shinnn** [comment]
No, gulp-eslint supports `.eslintrc.json`. Here is the evidence.

`./.eslintrc.json`

```json
{
  "rules": {
    "camelcase": "error"
  }
}
```

`./test.js`

```js
'use strict';

const eslint = require('gulp-eslint');
const File = require('vinyl');

eslint()
.on('data', file => {
  console.log(file.eslint.messages[0].message);
  //=> "Identifier 'a_b' is not in camel case."
})
.end(new File({
  path: 'fixture.js',
  contents: Buffer.from('a_b = c')
}));
```

```
$ node -v
v6.3.0

$ npm -v
3.10.5

$ node test.js
Identifier 'a_b' is not in camel case.
```

You're doing something wrong.

**Comment by talha-asad** [comment]
Yes my bad, it is working. I thought cause your readme specifically mentions only `.eslintrc` maybe it didn't read the json variant. Perhaps you should mention that in the readme as well?
