### ISSUE TITLE
indent: [2, "tab"] - does not pick up single space

### ISSUE THREAD

**Issue by julesmoretti** [adametry/gulp-eslint#173]
I would like everything to be tabbed but if at the start of a function I have 1 space it does not error out like so:

```
 const hello = () =>{
	console.log('thats it!' );
};

hello();
```

Recap:
```
(space)const hello...
(tab)console.log(...
};
```

The first space does not get returned as an error. This is my config file:

```
{
	"env": {
		"es6": true
	},
	"rules": {
		"indent": [2, "tab"]
	}
}

```

How can I go about fixing this issue?

**Comment by shinnn** [comment]
http://eslint.org/docs/developer-guide/contributing/reporting-bugs http://www.catb.org/esr/faqs/smart-questions.html#forum
