### ISSUE TITLE
globals should be an Object rather than an Array

### ISSUE THREAD

**Issue by ibc** [adametry/gulp-eslint#177]
http://eslint.org/docs/user-guide/configuring#specifying-globals

However, passing an Object to `globals` fails in gulp-eslint:

```
TypeError: (options.globals || []).reduce is not a function
```

**Comment by shinnn** [comment]
> passing an Object to `globals` fails

Intended. See https://github.com/eslint/eslint/pull/6922.

**Comment by ibc** [comment]
Well, certainly the issue is in `eslint` package itself:

```
TypeError: (options.globals || []).reduce is not a function
    at new Config (/xxxxxx/myApp/node_modules/eslint/lib/config.js:211:44)
```

It is `eslint` 3.4.0...

**Comment by ibc** [comment]
Thanks for the link.

**Comment by shinnn** [comment]
> certainly the issue is in `eslint` package itself

Yes, I also feel strange with the type difference of `global` between `.eslintrc` and API.

**Comment by matthew-dean** [comment]
I don't understand why this issue is closed. Defining an object for globals in `.eslintrc` seems to break gulp-eslint. That's not intended by the ESLint team.

**Comment by shinnn** [comment]
> I don't understand why this issue is closed.

Understand.

>  Defining an object for globals in .eslintrc seems to break gulp-eslint.

No.

`.eslintrc.js`:

```js
'use strict';

module.exports = {
  extends: 'eslint:recommended',
  globals: {
    foo: true
  }
};
```

`example.js`:

```js
'use strict';

const {join} = require('path');
const File = require('vinyl'); // v2.1.0
const gulpEslint = require('gulp-eslint'); // v4.0.0

//=> increments error count by the error "'foo' is not defined" if no `globals` is specified
const contents = Buffer.from('foo();');

gulpEslint()
.pipe(gulpEslint.results(results => {
  console.log(results);
}))
.end(new File({
  path: join(__dirname, 'fixture.js'),
  contents
}));
```

```
$ node -v
v9.2.0

$ node example.js
[ errorCount: 0, warningCount: 0 ]
```

**Comment by shinnn** [comment]
https://github.com/eslint/eslint/issues/7967#issuecomment-346707070

> This is definitely still an issue in the latest gulp-eslint.

No.

> the issue is that gulp-eslint cannot just pass the .eslintrc object to the ESLint JS API.

You're totally misusing gulp-eslint.

> This issue is incorrectly closed.

No.

**Comment by matthew-dean** [comment]
> You're totally misusing gulp-eslint.

?

Is the only difference that `gulp-eslint` can't be actually used in a Gulp stream? This is my code.

```js
import { globs } from './gulp-config';
import gulp from 'gulp';
import eslint from 'gulp-eslint';
import gulpif from 'gulp-if';

const SRC = globs.src.js.concat(
    globs.test.js,
    globs.demoapp.js,
    globs.config.js
);

gulp.task('lint:js', () => {
        return gulp.src(SRC)
            .pipe(eslint())
            .pipe(gulpif(
                eslint.format('checkstyle', reportFile),
                eslint.format()
             ));
    });
```
The above example works in `gulp-eslint` v1 and v2, just not v3 and v4. So I'm not sure how you can dismissively argue I'm "misusing" it, unless this Gulp plugin is not intended for Gulp?

**Comment by shinnn** [comment]
> Is the only difference that `gulp-eslint` can't be actually used in a Gulp stream?

No.

**Comment by dpikt** [comment]
Those are some pretty rude responses @shinnn. People are just trying to figure out how to fix their code.

Anyway, in my case I just updated my config to use the new array syntax. It's definitely confusing that the Node API fails with the object syntax but the CLI doesn't!

**Comment by matthew-dean** [comment]
@dpikt Right? What an asshole. Jesus Christ.

The only difference I can see is defining rules as a module (`.eslintrc.js` vs the default `.eslintrc`), with `gulp-eslint` perhaps only supporting the former. Oh well.  ¯\_(ツ)_/¯

**Comment by shinnn** [comment]
> `gulp-eslint` perhaps only supporting the former.

You can test it by yourself before posting totally incorrect comment here. You have your own brain.

`.eslintrc`

```json
{
  "root": true,
  "extends": "eslint:recommended",
  "globals": {
    "foo": true
  }
}
```

`gulpfile.js` and `source.js` are the same as https://github.com/adametry/gulp-eslint/issues/177#issuecomment-346915205.

```console
$ gulp
[11:12:08] Using gulpfile ~/example/gulpfile.js
[11:12:08] Starting 'default'...
[11:12:08] Finished 'default' after 265 ms
```

**Comment by shinnn** [comment]
> Those are some pretty rude responses

@dpikt Thank you for sympathy. Yes, unfortunately, some people cannot be honest to admit their own mistake but just blame their ignorance for OSS maintainers. 

> People are just trying to figure out how to fix their code.

Yeah, I hope everyone use StackOverflow for support questions and do not abuse OSS issue trackers. Probably the easiest trap for beginners to fall into though.

---

 I'm going to lock this issue down. Probably there won't be any productive discussion here any more.
