### ISSUE TITLE
Extends doesn't work anymore?

### ISSUE THREAD

**Issue by saviomd** [adametry/gulp-eslint#180]
It did work with 2.1.0 but doesn't with 3.0.1.

Throws an `Error: No ESLint configuration found.` using 3.0.1:
```
"extends": "xo/browser",
"env": {
	"es6": false,
	"jquery": true
}
```

***

If I insert a rules object, the error goes away:
```
"extends": "xo/browser",
"rules": {
	"eqeqeq": "error"
},
"env": {
	"es6": false,
	"jquery": true
}
```
But doing this, the rules that xo sets (through eslint-config-xo in my package.json), aren't loaded.
It only checks for the one rule I had set.

**Comment by shinnn** [comment]
No, it works in v3.10. too. https://github.com/adametry/gulp-eslint/commit/b0c281652d058b6962ad9501dba484ff1ea85e1e

**Comment by saviomd** [comment]
Hi shinn,
something in gulp-eslint DID change between 2.1.0 and 3.0.1 (or maybe in eslint itself? I saw that gulp-eslint 2.1.0 used eslint 2.10.0 and gulp-eslint 3.0.1 uses eslint 3.0.0).

I managed to make it work now using path.join (it's what eslint-config-xo/browser.js uses to extend eslint-config-xo/index.js), instead of require (like I used to do with gulp-eslint 2.1.0 and still do with other plugins, like stylelint).
Is this the way to go? Is there a better solution? I thought that it's very weird and require was more obvious to understand what is happening.

```
var eslintConfig = require('eslint-config-xo'); // works, doesn't have extends
var eslintConfig = require('eslint-config-xo/browser.js'); // doesn't works, have extends (worked in 2.1.0)
var eslintConfig = path.join(__dirname, 'node_modules', 'eslint-config-xo', 'browser.js'); // works, but is f****** ugly and complicated to understand

gulp.task('js', function() {
	return gulp.src('js/*.js')
		.pipe(eslint(eslintConfig))
		.pipe(eslint.format())
		.pipe(concat('dist.js'))
		.pipe(gulp.dest('js'))
});
```

**Comment by shinnn** [comment]
> f****** ugly and complicated to understand

Locking conversation for impoliteness of the issue author.
