### ISSUE TITLE
Re-introduce support for non-array format "globals" option

### ISSUE THREAD

**Issue by houdmont** [adametry/gulp-eslint#184]
Why was support dropped for non-array format "globals" option?

The eslint docs (http://eslint.org/docs/user-guide/configuring#specifying-globals) still document globals as being an object, where `true` and `false` values for each object key hold different meaning.

Forcing globals to be defined as an array when using gulp-lint seems to be contrary to a "normal" eslint config file?

**Comment by shinnn** [comment]
> The eslint docs (http://eslint.org/docs/user-guide/configuring#specifying-globals) still document globals as being an object, where `true` and `false` values for each object key hold different meaning.

The link you posted is not ESLint API docs but ESLint config *file* docs.

> Why was support dropped for non-array format "globals" option?


To make gulp-eslint API "normal", as you said.

**Comment by shinnn** [comment]
I removed the link to http://eslint.org/docs/user-guide/configuring#specifying-globals from README. That was confusing.
