### ISSUE TITLE
Using `extends` in ESlint settings causes an error

### ISSUE THREAD

**Issue by mischah** [adametry/gulp-eslint#186]
Hej there,

it’s seems like it is like already reported in #180 

Using `extends` in ESLint settings causes ESlint to fail with: 
```
Uncaught Error: No ESLint configuration found.
```

See https://travis-ci.org/yeoman/generator-generator/jobs/181159849

**Comment by shinnn** [comment]
> Using `extends` in ESlint settings causes an error

No.

You're misusing gulp-eslint API.

**Comment by mischah** [comment]
Hej Shinnosuke,

sorry, but I don’t get it. Could you be so kind to explain?

I had a the following setup:

`.eslintrc.json`:
```
{
  "extends": "xo-space",
  "env": {
    "node": true,
    "mocha": true,
    "es6": true
  }
}
```

`xo-space` comes from `"eslint-config-xo-space": "^0.15.0"` within my `package.json`.

Excerpt from `gulpfile.js`:
```
gulp.task('static', function () {
  return gulp.src('**/*.js')
    .pipe(excludeGitignore())
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError());
});
```

It works locally like a charm. (Mac OS X, Node 6.9.1)

But failed on travis for all configured node versions:
https://travis-ci.org/yeoman/generator-generator/builds/181137258

Any help is appreciated 💖 

Thanks, Michael

**Comment by shinnn** [comment]
I'm confused that:

1. You wrote "See https://travis-ci.org/yeoman/generator-generator/jobs/181159849" and that commit includes, as i said, [misuse of gulp-eslint API](https://github.com/yeoman/generator-generator/commit/4a76c5ab75cb2c02c95e8642481d580f9ee8e064).
2. Then you pasted totally different code in https://github.com/adametry/gulp-eslint/issues/186#issuecomment-264729444.

Which code should I review?

**Comment by mischah** [comment]
Soory, the misuse was an attempt to fix the issue I had. 

The pasted code relates to https://travis-ci.org/yeoman/generator-generator/builds/181137258

But the error first appeared a few commits earlier after upgading gulp-eslint from 2.x to 3.x:
https://travis-ci.org/yeoman/generator-generator/jobs/181037513

To that time we still had an `.eslintrc`without a shared config but with an `extend`.
See https://github.com/yeoman/generator-generator/blob/51fb745a40100804845bd7e4dde78af73d51c9d3/.eslintrc.json

**Comment by mischah** [comment]
Would it help to setup a minimal test case repo?

**Comment by shinnn** [comment]
Hmm,

1. Cloned [the last revision](https://github.com/yeoman/generator-generator/commit/d187e66212800ce9967d8de05a2d09edbb67228c) of https://github.com/yeoman/generator-generator/pull/170.
2. Updated [this line](https://github.com/yeoman/generator-generator/blob/d187e66212800ce9967d8de05a2d09edbb67228c/package.json#L41) from `"^2.0.0"` to `"^3.0.0"`.
3. `npm install && test`
4. Passed all tests, contrary to the CI build result.

@mischah Can you reproduce the test failure in your local machine?

> Would it help to setup a minimal test case repo?

Yes, really helpful.

**Comment by mischah** [comment]
> @mischah Can you reproduce the test failure in your local machine?

Nope. Sadly not 😞 

I hope to find time to set up a test repo tomorrow.

**Comment by mischah** [comment]
Hej,

here is a minimal test repo:
https://github.com/mischah/gulp-eslint-issue-186

No problems with extending settings. Neither local nor on travis.

I have no clue what’s different with the yeoman repo. Guess I need to investigate further.

Thanks for having a look :octocat:

**Comment by cowwoc** [comment]
@shinnn I am seeing the exact same problem without using yeoman.

Here is a self-contained testcase:

gulpfile.js
```
var gulp = require("gulp");
var eslint = require("gulp-eslint");

gulp.task("lint", function()
{
	return gulp.src(
		[
			"gulpfile.js",
			"src/**.js",
			"test/**.js"
		]).
		pipe(eslint({
				extends: "eslint:recommended"
			}
		)).
		pipe(eslint.format()).
		pipe(eslint.failOnError());
});

gulp.task("default", ["lint"]);
```

packages.json:
```
{
	"name": "foobar.js",
	"version": "1.0.0",
	"contributors": [],
	"dependencies": {},
	"devDependencies": {
		"gulp": "^3.9.1",
		"gulp-eslint": "^3.0.1"
	}
```

I am seeing this under Windows 10 64-bit, node 6.9.2. I hope this helps.

Are you able to reproduce this on your end?

**Comment by cowwoc** [comment]
Key point for my testcase though: there is no external `.eslintrc` file. Maybe that makes a difference.

**Comment by shinnn** [comment]
@mischah I added `delete require.cache(require.resolve('.eslintrc.json'))` to [this line](https://github.com/yeoman/generator-generator/blob/640bdc558f498275681bc57666e1f995b8e5bc2f/gulpfile.js#L37) and the problem was fixed. So this issue is not directly related to gulp-eslint, but a bug of file caching mechanism introduced by other modules, (Yeoman test tools, ESLint etc.)

@cowwoc 

> I am seeing the exact same problem without using yeoman.

No. You're just misusing gulp-eslint API.

**Comment by cowwoc** [comment]
@shinnn Sorry, can you please clarify what about my testcase constitutes a "misuse of the API"?

If I replace:
```
pipe(eslint({
	extends: "eslint:recommended"
})).
```
by:
```
pipe(eslint({
	extends: "eslint:recommended",
	"rules": {
		"semi": 2
	}
})).
```

then the problem goes away (the error message goes away and ESLint outputs a normal report). How could that be related to a misuse of the API?

**Comment by shinnn** [comment]
@cowwoc I just updated the previous comment. https://github.com/adametry/gulp-eslint/issues/186#issuecomment-271283218

**Comment by cowwoc** [comment]
@shinnn Thank you for elaborating. That explanation makes a lot more sense.

**Comment by cowwoc** [comment]
For other people who run across this issue in the future, see https://github.com/eslint/eslint/issues/7108#issuecomment-246120036 for a related discussion (and possible workarounds).

**Comment by cowwoc** [comment]
@shinnn In case you're interested, if you change gulp-eslint to wrap the code mentioned at https://github.com/eslint/eslint/issues/7108#issuecomment-246120036 (using either `CLIEngine.executeOnText()` or `CLIEngine.executeOnFiles()`) then users will be able to use `extends` through the API.

**Comment by mischah** [comment]
Thanks for the feedback. This is how i fixed it:
https://github.com/yeoman/generator-generator/pull/184/files
