### ISSUE TITLE
Plugin should ignore .eslintrc.json when configuration argument is present

### ISSUE THREAD

**Issue by cowwoc** [adametry/gulp-eslint#188]
If a user passes a configuration into `pipe(eslint())` and a `.eslintrc.json` file is present, then the plugin should ignore the external configuration.

Otherwise, the internal configuration is getting ignored silently.

**Comment by shinnn** [comment]
No. Use `useEslintrc` option.

**Comment by cowwoc** [comment]
@shinnn Thanks, but shouldn't you at least output a warning message if the user provides a configuration argument and `useEslintrc` is undefined?

**Comment by shinnn** [comment]
@cowwoc gulp-eslint is just a wrapper of [ESLint API](http://eslint.org/docs/developer-guide/nodejs-api). So if you'd like to suggest changes in the default bahavior, for example warning message, open a new issue on the [ESLint issue tracker](https://github.com/eslint/eslint/issues) instead. If the ESLint team accept your proposal, of course gulp-eslint happily follows it.

**Comment by cowwoc** [comment]
@shinnn Makes sense. Thanks for the clarification.
