### ISSUE TITLE
Upgrade eslint

### ISSUE THREAD

**Issue by cowwoc** [adametry/gulp-eslint#189]
The current version of eslint is from March 2016. Please upgrade to the latest version possible so we can get our hands on all those new es6 rules.

**Comment by shinnn** [comment]
No thanks. Read https://nodesource.com/blog/semver-tilde-and-caret/ and learn how [`^` in package.json](https://github.com/adametry/gulp-eslint/blob/6059c2245c677a48add3ca4bbe5912f601732826/package.json#L44) works.

**Comment by cowwoc** [comment]
@shinnn Thank you for the clarification. What's the easiest way to upgrade transitive dependencies? Is `npm-shrinkwrap` the only way?

**Comment by shinnn** [comment]
Use https://stackoverflow.com/ for non project-related questions.

**Comment by BreaGaudioso** [comment]
It doesn't make much sense that you wouldn't want to make this package as user friendly as possible. If there is more functionality available, why not upgrade? It's a single line change.

**Comment by shinnn** [comment]
@BreaGaudioso Read https://github.com/adametry/gulp-eslint/issues/189#issuecomment-271485125 again.
