### ISSUE TITLE
Update ESLint from 3.x to 4.x

### ISSUE THREAD

**Issue by soda0289** [adametry/gulp-eslint#196]
Currently gulp-eslint package.json only installs eslint v3. With the soon to be released eslint v4 it would be nice if gulp-eslint could be upgraded as well. Do we need to have eslint as dependency? Would a peer dependency work as well?

**Comment by shinnn** [comment]
> Would a peer dependency work as well?

No.

**Comment by soda0289** [comment]
@shinnn Is this sufficient https://github.com/adametry/gulp-eslint/pull/197
