### ISSUE TITLE
outdated dependencies

### ISSUE THREAD

**Issue by DarkPark** [adametry/gulp-eslint#20]
would be nice to update packages as some of them rather old
"eslint": "^0.9.2" vs current 0.10.2
it leads to some problems with Webstorm IDE and total failure on some not trivial setups due to wrong path resolution in the eslint 0.9.*
just to check I've manually corrected the version of eslint in your package.json and all problems have dissapeared

**Comment by qorbani** [comment]
@adametry is there any timeframe to update dependencies?

**Comment by rtorino** [comment]
@adametry, we'e also waiting for this, we're using new rules/renamed rules (space-unary-word-ops renamed to space-unary-ops since v0.10.0) that are not supported in the current eslint dependency.

**Comment by adametry** [comment]
It's not using eslint 0.13. Apologies for the delay.

**Comment by DarkPark** [comment]
thanks

**Comment by rtorino** [comment]
Thanks!

**Comment by MethodGrab** [comment]
:+1: Thanks!
