### ISSUE TITLE
eslint-disable comment not respected in file

### ISSUE THREAD

**Issue by tetreault** [adametry/gulp-eslint#201]
Hello, I am using gulp-eslint for a small project. I had one library file I wanted skipped over:  `src/js/tether.min.js`. I added this in my .eslintignore file and gulp-eslint was still picking it up even though it skips over the `node_modules` folder properly. I also tried tossing `/* eslint-disable */` at the top of one of the files had no effect. It was only this one file that wasnt respected, though, and I'm at a loss as to why. So in the meantime I've just removed it as it wasn't crucial to the project. If there's any further info I can provide to help isolate why this might have happened, just let me know!

Setup:
gulp-eslint: ^4.0.0
NPM: 5.0.3
Node: v7.2.0

**Comment by shinnn** [comment]
@tetreault Can you create a small Github repository to reproduce the problem?

> Node: v7.2.0

Don't use 7.x. It's no longer maintained. https://github.com/nodejs/LTS

**Comment by shinnn** [comment]
No feedback.
