### ISSUE TITLE
Unable to run `fix` mode. Maybe recent version of eslint works differently?

### ISSUE THREAD

**Issue by trusktr** [adametry/gulp-eslint#204]
I'm trying to run `fix` mode, but I can't seem to get it working. Based on your example and [this issue](https://github.com/adametry/gulp-eslint/issues/99), I'm trying something like

```js
function isFixed(file) {
  return file.eslint != null && file.eslint.fixed
}

gulp.task('lint', () =>
  gulp
    .src(['**/*.js', '!node_modules/**'])
    .pipe(eslint({ configFile: './.eslintrc', fix: true }))
    .pipe(eslint.format())
    .pipe(gulpIf(isFixed, gulp.dest('./')))
    .pipe(eslint.failAfterError())
)
```

but this isn't running the auto fix.

I'm using `prettier` in my eslintrc, like this:

```js
{
  "extends": [
    "airbnb",
    "prettier",
  ],
  "plugins": [
    "prettier",
  ],
  "env": {
    "browser": true,
    "node": true,
    "mocha": true,
  },
  "settings": {
    "import/resolver": "node",
  },
  "rules": {
    "prettier/prettier": ["error", {
      "printWidth": 80,
      "tabWidth": 2,
      "useTabs": false,
      "semi": false,
      "singleQuote": true,
      "trailingComma": "all",
      "bracketSpacing": true,
      "jsxBracketSameLine": false,
    }],
    "arrow-parens": 0,
    "no-unused-vars": [
      "error",
      {
        "argsIgnorePattern": "^_",
      },
    ],
    "jsx-a11y/href-no-hash": 0,
    "comma-dangle": [
      "error",
      {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "always-multiline",
        "exports": "always-multiline",
        "functions": "never",
      },
    ],
  },
}
```

and while I don't see any fixes happening, I do see prettier warnings in the console, f.e.

```
/Users/jpea/src/westfield+onboarding/gulpfile.js
  28:15  error  Replace `'·---------·file·eslint?',·file.eslint·&&·Object.keys(file.eslint)` with `⏎····'·---------·file·eslint?',⏎····file.eslint·&&·Object.keys(file.eslint),⏎··`  prettier/prettier
```

I also tried this:

```js
function isFixed(file) {
  console.log('eslint fixed?', file.eslint && file.eslint.fixed)
  return file.eslint != null && file.eslint.fixed
}
```

and the output is always

```
eslint fixed? undefined
```

There's never a `fixed` property.

Am I missing something?

**Comment by shinnn** [comment]
Can you create a small Github repository to reproduce the problem?

**Comment by trusktr** [comment]
@shinnn Hello Shin, here's a repo: https://github.com/trusktr/gulp-eslint/tree/issue-204

Seems like it actually is fixing stuff, but not everything. After you `npm i`, run `./node_modules/.bin/gulp lint` and it will modify the `foo.js` and `gulpfile.js` files, but it won't modify the `foo.hbs` file. Also notice that even though it modified parts of the files, it still throws an error for some of them.

Maybe this is an issue with the prettier plugin.

**Comment by shinnn** [comment]
> it won't modify the `foo.hbs` file.

Yes, because your glob pattern `['**/*.js', '!node_modules/**']` doesn't match any `.hbs` files.

**Comment by trusktr** [comment]
@shinnn If you look a little more closely, you'll see it `merge`s two streams, with two patterns, there is also

```js
      .src(['**/*.hbs', '!node_modules/**'])
```

No fixes seems to be applied to the hbs files, but only partial fixes are applied to the js files.

Seems like there may be two issues:

1. prettier fixes are overriden by eslint for the .js files, so only some of the prettier errors are fixed?
1. No fixes are applied at all to the .hbs files. An eslint problem?

**Comment by shinnn** [comment]
> It merges two streams

Oh, I missed that.

Can you reproduce the same problem with ESLint CLI, or is it a gulp-specific problem?

**Comment by trusktr** [comment]
It turns out it is eslint's fault: https://github.com/eslint/eslint/issues/9142#issuecomment-324183928
