### ISSUE TITLE
Create a branch @es6jsx

### ISSUE THREAD

**Issue by oziks** [adametry/gulp-eslint#21]
To track testing jsx support, it would be nice to create a branch with eslint dependence in v0.11.0-alpha.0 ?!

**Comment by gilbarbara** [comment]
@oziks I was hoping for that too but since this repo is still using 0.9.2, I made a fork with eslint 0.11.0-alpha.0 for testing.
https://github.com/gilbarbara/gulp-eslint

**Comment by oziks** [comment]
@gilbarbara thanks, but I've already created :)
https://github.com/oziks/gulp-eslint/tree/es6jsx

**Comment by adametry** [comment]
An update has been publishes that uses eslint 0.13.0. Try it out and let me know if it works for you.

**Comment by oziks** [comment]
It's work fine, thanks !
