### ISSUE TITLE
Add option to enable reportUnusedDisableDirectives

### ISSUE THREAD

**Issue by eTorAken** [adametry/gulp-eslint#211]
Since eslint@4.8.0, there is a new option which, if enabled, reports for unused disable directives (such as `eslint-disable`, `eslint-disable-line`, `eslint-disable-next-line`).

To use it, there is a command line option ([`--report-unused-disable-directives`](https://eslint.org/docs/user-guide/command-line-interface#report-unused-disable-directives)) and a CLIEngine option ([`ReportUnusedDisableDirectives`](https://eslint.org/docs/developer-guide/nodejs-api#cliengine)).

Is there a chance this option could be implemented for gulp-eslint?

**Comment by shinnn** [comment]
It's already implemented.

**Comment by eTorAken** [comment]
Sorry, I didn't see that CLIEngine was part of gulp-eslint.

For those wondering, here is a sample:
```jsx
gulp.task('lint', () => {
  return gulp.src(['**/*.js','!node_modules/**'])
    .pipe(eslint({ reportUnusedDisableDirectives: true }))
    .pipe(eslint.format())
    .pipe(eslint.failAfterError());
});
```
