### ISSUE TITLE
Eslint format never triggers end event

### ISSUE THREAD

**Issue by jasonlav** [adametry/gulp-eslint#212]
It appears that `eslint.format()` method prevents Gulp from triggering an on.end event. Issue occurs regardless of ESLint errors or warnings. `script.js` can be blank and it still occurs. See issue example below.

```js
var gulp = require('gulp');
var eslint = require('gulp-eslint');

gulp.task('default', function() {
	gulp.src('script.js')
	.pipe(eslint({
		rules: {
			"no-cond-assign": 2
		}
	}))
	.pipe(eslint.format())
	.on('end', function() {
		console.log("end"); //End never gets logged
	});
});
```

**Comment by shinnn** [comment]
Intended. Node.js `Writable` stream never emits `end` events. https://nodejs.org/api/stream.html
