### ISSUE TITLE
Drop dependency on deprecated `gulp-util`

### ISSUE THREAD

**Issue by demurgos** [adametry/gulp-eslint#214]
Hi,
[`gulp-util`](https://github.com/gulpjs/gulp-util) is deprecated. It should be replaced by dependencies on the individual components used by `gulp-eslint`. The README lists alternatives for the different components.

**Comment by shinnn** [comment]
Use Github search before opening new issues. https://github.com/adametry/gulp-eslint/pulls?q=is%3Apr+remove+gulp-util

**Comment by demurgos** [comment]
Thanks, I searched in the issues instead of a full repo search. Sorry for the duplicate.
