### ISSUE TITLE
"Definition for rule 'no-tabs' was not found" when running gulp-eslint

### ISSUE THREAD

**Issue by maeriens** [adametry/gulp-eslint#217]
Hello! I am facing an issue when running `eslint` via `gulp`. This is rather a question than an issue.

 In my configuration, I have several rules, and recently added `no-tabs`. Running `eslint` detects it and correctly warns me, but when I run any `gulp` task, where I have the `lint` as a middleware, it is always throwing the error `1:1  error    Definition for rule 'no-tabs' was not found    no-tabs`.

 I tested the rule against both local and global `eslint` and the rule is recognized, but the issue happens always when I run the `gulp` task.
 
#### Dev dependencies in `package.json`:
- "eslint": "^4.16.0",
- "eslint-plugin-json": "^1.2.0"
- "eslint-plugin-mocha": "^2.2.0"
- "gulp-eslint": "^2.1.0

#### Lint task
_Note: I load all the plugins by doing `const Plugins = require('gulp-load-plugins')`_
```javascript
gulp.task('lint-subset', 'Lint a subset of JS files.', () => {
    // default to all paths if glob pattern does not exist
    let globPattern = argv.glob || paths.all;
    return gulp.src(globPattern)
        .pipe(Plugins.eslint())
        .pipe(Plugins.eslint.format());
}, options);
```

#### Gulp task
```javascript
gulp.task('subset', 'Run a subset of tests.', ['lint-subset'], () => {
        gulpTaskSetup('{env}', 'subset', argv.grep || '');
    }, options);
```

Any help or pointers as to why is this happening would be awesome.

**Comment by shinnn** [comment]
> "gulp-eslint": "^2.1.0

Upgrade.
