### ISSUE TITLE
How don't show message if not exist errors and warnings

### ISSUE THREAD

**Issue by HawkeyePierce89** [adametry/gulp-eslint#221]
![image](https://user-images.githubusercontent.com/25603805/36087238-ed0e4f08-1003-11e8-9a37-66bab2347b60.png)
How I can hide this message if errors and warnings do not exist?

**Comment by shinnn** [comment]
This is not an issue directly related to gulp-eslint. Submit it to https://gitter.im/eslint/eslint or elsewhere.
