### ISSUE TITLE
no-unused-vars if defined in for loop

### ISSUE THREAD

**Issue by alishah-edgy** [adametry/gulp-eslint#241]
for (const key in block) {
      console.log(key);
    }

it gives me error
"error  'key' is defined but never used  no-unused-vars"

**Comment by silviuburceadev** [comment]
I think this is an issue that belongs to ESLint directly.

**Comment by alishah-edgy** [comment]
Ok Thank you.
For anyone who stumbles upon this same issue. Workaround is to define variable before loop.
let key =  null;
for (key in block) {
  console.log(key);
}
