### ISSUE TITLE
Why the difference between gulp-eslint configuration and official eslint configuration regarding globals?

### ISSUE THREAD

**Issue by valoricDe** [adametry/gulp-eslint#252]
Hello there. Why is the globals fields in the gulp-eslint configuration not of the same shape of the eslint configuration?
I just updated gulp-eslint and got the error "Error: globals must be an array."
And was a bit confused of it.
Cheers

**Comment by fasttime** [comment]
gulp-eslint uses the now deprecated [`CLIEngine` API](https://eslint.org/docs/6.0.0/developer-guide/nodejs-api#cliengine), where `globals` is expected to be, as per the docs
> An array of global variables to declare (default: empty array). Corresponds to `--global`, and similarly supports passing `'name:true'` to denote a writeable global. Note: This differs from `.eslintrc.*` / `baseConfig`, where `globals` is an object.

**Comment by valoricDe** [comment]
So gulp-eslint is reading the configuration from .eslintrc.json using the CLIEngine to provide the eslint configuration.
But this clashes directly with the second sentence you gave that is should be an object right?
So I would either not load it from .eslintrc.json by default or map the object to an array otherwise other plugins which are depending on the eslintrc.json structure will break.

I got rid of the error with duplicating the eslintrc.json and using https://github.com/adametry/gulp-eslint#eslintconfigfilepath

**Comment by fasttime** [comment]
I was talking about the `globals` property in the [options](https://github.com/adametry/gulp-eslint#optionsglobals) argument passed to gulp-eslint. That is not the same as the `globals` setting in `.eslintrc.json`.

**Comment by valoricDe** [comment]
Ok thank you. I mixed those up
