### ISSUE TITLE
Error: Definition for rule 'nodeca/indent' was not found.

### ISSUE THREAD

**Issue by moroshko** [adametry/gulp-eslint#28]
I use [eslint-plugin-nodeca](https://github.com/nodeca/eslint-plugin-nodeca) to check indentation.

When I run `node_modules/eslint/bin/eslint.js src/app.js`, eslint runs properly.

But, when I run `gulp lint` I get the following error:

    Error: Definition for rule 'nodeca/indent' was not found.

What am I missing here?

To check the gulp task and the eslint config, have a look [here](https://github.com/moroshko/react-playground).

**Comment by shinnn** [comment]
Use [eslint issue tracker](https://github.com/eslint/eslint/issues). This repo is **gulp-**eslint.

**Comment by moroshko** [comment]
I don't think it is eslint's problem. As I pointed out, Running eslint (`node_modules/eslint/bin/eslint.js src/app.js`) works fine.

But, using the `gulp-eslint` plugin causing an error.

Am I missing something?

**Comment by shinnn** [comment]
Ah, sorry! I've totally misread your comment. I'll check it later.

**Comment by adametry** [comment]
I was able to figure out a way to trigger filesystem-local plugin loading without duplicating eslint code. This fix has been published as version 0.3.0.

**Comment by moroshko** [comment]
Thanks a lot for a quick fix!
