### ISSUE TITLE
Updating to eslint 0.14.0 would be most appreciated

### ISSUE THREAD

**Issue by doberkofler** [adametry/gulp-eslint#29]
Would it actually not make sense to make the eslint dependency more generic, at least before 1.0.0 is out ?

**Comment by shinnn** [comment]
Read this. https://github.com/adametry/gulp-eslint/pull/19#issuecomment-71404986

**Comment by shinnn** [comment]
Updated. 1aaf6c69eb2bbd4048e564b6856a7299afdbbda1

**Comment by doberkofler** [comment]
Thank you for your quick feedback. Can we also soon expect a new npm package?

**Comment by message** [comment]
Can you bump a npm package update?

**Comment by shinnn** [comment]
Released v0.4.0.
