### ISSUE TITLE
rulesPaths not working

### ISSUE THREAD

**Issue by lomteslie** [adametry/gulp-eslint#34]
Hey there. I've been banging my head against the wall with this for some time now. The `rulesPaths` option does not seem to want to load my custom rules. `'eslint/custom-rules'` is a directory with a single custom rule, as defined in the custom config file. The `rulesdir` option has the same behavior. I only noticed this after I updated gulp-eslint to version 0.4.2. Any help or insight would be appreciated. Thanks.

**Task:**

    gulp.task('lint:js', function() {
		return gulp.src(config.paths.src.js)
			.pipe(eslint({
				configFile: 'eslint/config.json',
				rulesPaths: ['eslint/custom-rules'],
				globals: {
					'angular': false,
					'jQuery': false
				},
				useEslintrc: false
			}))
			.pipe(eslint.format());
	});

**Error:**

    /node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:603
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
    Error: Definition for rule 'custom-no-multi-space' was not found.

**config.json**

    ...
    "no-multi-spaces": 0,
    "custom-no-multi-space": 2,
    "no-native-reassign": 2,
    ...

**Comment by adametry** [comment]
Try changing "rulesPaths" to "rulePaths". That's a typo in the readme and source (when migrating "rulesdir" to "rulePaths"). Published 0.4.3 to fix the typo.

Let me know if this resolves your issue.

**Comment by lomteslie** [comment]
Ah, I should have caught that. That did it. Thanks for the fix!
