### ISSUE TITLE
Parser option

### ISSUE THREAD

**Issue by ai** [adametry/gulp-eslint#39]
I want to use babel-eslint, but seems like there is no `parser` option.

/cc @shinnn @adametry

**Comment by shinnn** [comment]
You can set `"parser"` option in `.eslintrc`.

**Comment by ai** [comment]
Temporary I put it there, but missed `parser` option in Gulp plugin seems like inconsistent behavior.

**Comment by shinnn** [comment]
This is because ESLint API doesn't accept `parser` option. We can set it only with `.eslintrc`  for the moment.

**Comment by adametry** [comment]
Currently, eslint doesn't move the 'parser' option from the CLIEngine to the file-specific config; however, there does seem to be one route that works currently: baseConfig.

Try this:
```javascript
gulp.task('lint', function() {
	return gulp.src(['**/*.js'])
		.pipe(eslint({
			baseConfig:{
				parser: "babel-eslint"
			}
		}))
		.pipe(eslint.format());
});
```

The drawback on this one is that it effectively sets the "reset" option. If you already configure the eslint rules, this may not be a problem.

**Comment by adametry** [comment]
For what it's worth, eslint is [considering](http://eslint.org/blog/2015/05/eslint-0.21.0-released/#1.0.0-update) clearing the baseConfig by default in v1.0.0.

**Comment by IanVS** [comment]
FWIW: There is an accepted issue at ESLint (https://github.com/eslint/eslint/issues/3127) to be able to specify parser from the CLI (and CLIEngine).  It is currently waiting for someone to step up and implement it.

**Comment by jefferyasharp** [comment]
Setting the parser in .eslintrc gives the following error
{
  "parser": "babel-eslint",
  "rules": {
    "strict": 0
  }
}

0:0  error  Cannot find module 'babel-eslint'

It appears this package isn't included as a dependency for gulp-eslint. 
Are there any plans to incorporate it?

**Comment by adametry** [comment]
As @IanVS mentioned, Eslint added support for the "parser" option in CLIEngine. Gulp-eslint does very little aside from migrating legacy options before passing the config to CLIEngine. Effectively, the option can be used with gulp-eslint now as well.

**Comment by adametry** [comment]
@jefferyasharp, while we use `babel-eslint` to test parser support, there is no direct dependency on `babel-eslint` in "production" use. If your package uses `babel-eslint`, it should be installed as a dependency there. Also, there may be some installation method that cause Eslint to have trouble finding a parser, such as globally installing or (sym)linking to Eslint. If either of these are possible causes of the error you're experiencing, consider installing `babel-eslint` relative to the path `eslint` is installed.

If the issue remains, please create a separate issue to discuss and track it.
