### ISSUE TITLE
Add eslint.org URL to the Github repository description

### ISSUE THREAD

**Issue by shinnn** [adametry/gulp-eslint#41]
![image](https://cloud.githubusercontent.com/assets/1131567/5735869/0754fe1c-9c11-11e4-9cb2-ddbac065a448.png)

It's more useful for the users.

**Comment by adametry** [comment]
What benefit does this have over the esling.org link at the top of the readme?

**Comment by adametry** [comment]
I'm going to close this since a link already exists and there hasn't been much discussion on it.
