### ISSUE TITLE
No error is thrown when unknown parser is set in .eslintrc

### ISSUE THREAD

**Issue by gajus** [adametry/gulp-eslint#45]
```
{
    "parser": "foo-bar"
}
```

Does not thrown any error. Also, it would be useful if output would tell what parser is being used.

It silently ignores error:

```
Cannot find module 'foo-bar'
```

**Comment by shinnn** [comment]
PR welcome.

**Comment by adametry** [comment]
I see lint errors like:

```shell
/gulp-eslint/gulpfile.js
  0:0  error  Cannot find module 'foo-bar'
```

Combined with `failOnError` or `failAfterError`, the process will exit with an error code.

Is your experience different or are you expecting something else?

**Comment by adametry** [comment]
I'm closing this for now. If the issue persists, please provide some additional details.
