### ISSUE TITLE
Reflect in README.md: .formatEach() or.format() are needed for output.

### ISSUE THREAD

**Issue by Kingdutch** [adametry/gulp-eslint#46]
For most modules I use the workflow is:

    var module = require('gulp-module');
    
    // some task
    gulp.src(files).pipe(module()); //done

I tried this for gulp-eslint as well but this produces no output and no warnings or errors which seem to indicate a defective module so I quickly gave up. The first example in the README did specify eslint.format() but I thought it was just a weird configuration option like eslint.failOnError() listed below it.

Why are these separate streams instead of configuration options on the eslint module? The expected scenario would then become:

    var eslint= require('gulp-eslint');
    
    // some task
    gulp.src(files)
      .pipe(eslint({
         format: "each",
         failOnError: "true",
       }); //done

These options would also be sensible defaults. If I want it to fail on an error I don't really want to do anything else in the task anyway.

**Comment by adametry** [comment]
It's a common practice with gulp linters (e.g., [gulp-csslint](https://github.com/lazd/gulp-csslint), [gulp-gjslint](https://github.com/TomSeldon/gulp-gjslint), [gulp-coffeelint](https://github.com/janraasch/gulp-coffeelint), [gulp-jshint](https://github.com/spalger/gulp-jshint)).

I find it to be a flexible approach, allowing other modules to make use of the lint data (like [gulp-coffeelint-threshold](https://github.com/adam-lynch/gulp-coffeelint-threshold)) and non-console oriented applications (maybe some codekit-like app). It also supports the use of multiple reporters and linters before throwing failing the stream.

**Comment by Kingdutch** [comment]
Sounds like very valid use cases. Then perhaps could I change this to an update to the README.md? I'll comment with a suggestion soon.
