### ISSUE TITLE
eslint is at 0.18.0

### ISSUE THREAD

**Issue by justin808** [adametry/gulp-eslint#48]
Any chance on making dependencies like eslint a peerDependency so that they can be upgraded separately?

**Comment by adametry** [comment]
We tried that a while back. It only caused more problems (same version incompatibilities issue that come with any eslint update, plus peer dependency conflicts). For more detail see https://github.com/adametry/gulp-eslint/pull/19#issuecomment-71404986.

**Comment by adametry** [comment]
gulp-eslint has been updated to use eslint ^0.18.0.

**Comment by adametry** [comment]
Since eslint 0.18.x is covered, I'll close this issue. If you'd like to raise a discussion regarding the use of peerDependencies, it can take place as a separate issue.
