### ISSUE TITLE
Possible not to `errorOnFail` when watching?

### ISSUE THREAD

**Issue by kud** [adametry/gulp-eslint#50]
It's really cool to break the processs when there's an error in order not to push it in production but when I'm doing a "watch", I don't want a fail on error. Is it possible?

**Comment by adametry** [comment]
The error is thrown only when a eslinted file is passed through the ```errorOnFail``` stream/step. You might either avoid using the stream when watching (preferable) or downgrading errors to warnings with a custom formatter (semi-hacky). How simple this is to do depends largely on how your tasks are arranged.

**Comment by kud** [comment]
Sounds good to me, thanks. ;)
