### ISSUE TITLE
Use eslint instead of jscs

### ISSUE THREAD

**Issue by doberkofler** [adametry/gulp-eslint#55]
gulp-eslint is (still) using jscs but should (at least for consistency) rather switch to eslint

**Comment by shinnn** [comment]
This project uses JSCS only for development. JSCS supports some features that ESLint doesn't support.

> at least for consistency

Why do you think using JSCS is inconsistent?

**Comment by doberkofler** [comment]
Maybe inconsistent was a bad wording but given the fact that gulp-eslint is a gulp plugin for eslint and eslint (at least in my opinion) is a super-set of jshint and jscs it would feel more appropriate to use eslint as the linter for gulp-eslint. What features of jscs does eslint not yet support ?

**Comment by shinnn** [comment]
> What features of jscs does eslint not yet support ?

https://github.com/eslint/eslint/issues/1884

But, OK, now I basically agree with you. I'll update ESLint settings to cover JSCS features.
 
Thanks for your good proposal, @doberkofler.

**Comment by adametry** [comment]
gulp-eslint once again dogfood's itself.  I'm closing this. We can discuss dot formatting in a separate thread.
