### ISSUE TITLE
Repository doesn't have the last release tags

### ISSUE THREAD

**Issue by ifraixedes** [adametry/gulp-eslint#61]

**Comment by adametry** [comment]
Perhaps I misunderstood the issue, but each time this package is published on NPM, the dist-tag is updated to the latest version. The "latest" dist-tag for `gulp-eslint` is currently set to the most recent version (0.12.0). Are you experiencing a problem with this tag?

**Comment by ifraixedes** [comment]
I don't understand what you mean with `dist-tag`; my issue only referred about the repository.

Repository doesn't have the last tag version https://github.com/adametry/gulp-eslint/releases

It isn't a big deal, however sometimes I check the tags to know the last versions than to go to npm site or check `package.json`

**Comment by shinnn** [comment]
Totally agree with @ifraixedes. I often check the latest version number of the package by opening the [/releases](https://github.com/adametry/gulp-eslint/releases) page. I always create a new tag whenever I publish a new version to npm, but @adametry doesn't.

**Comment by adametry** [comment]
My mistake. I was thinking of npm tags (e.g., gulp-eslint@latest). I've tagged the commit for the v0.21.0 package.

**Comment by ifraixedes** [comment]
Cool for me, then you can close if @shinnn is happy

**Comment by shinnn** [comment]
@adametry, not `v0.21.0` but `v0.12.0` :(

**Comment by ifraixedes** [comment]
@adametry good catch, I'm quite sleepy so far

**Comment by adametry** [comment]
haha. Fixed. Thanks.
