### ISSUE TITLE
Format checkstyle outputs xml

### ISSUE THREAD

**Issue by mhartington** [adametry/gulp-eslint#62]
Not sure if this is on purpose, but if you use `checkstyle` in your format, it outputs  a string of xml instead of a formatted table.

```
[17:06:48] Starting 'lint'...
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="/Users/mhartington/GitHub/ionic-sf-demos/eslint/www/js/app.js"></file><file name="/Users/mhartington/GitHub/ionic-sf-demos/eslint/www/js/controllers.js"><error line="3" column="33" severity="error" message="$scope is defined but never used (no-unused-vars)" /><error line="9" column="3" severity="error" message="Missing semicolon. (semi)" /></file><file name="/Users/mhartington/GitHub/ionic-sf-demos/eslint/www/js/services.js"><error line="12" column="3" severity="error" message="A space is required after &apos;,&apos;. (comma-spacing)" /></file></checkstyle>[17:06:49] Finished 'lint' after 129 ms
```

As mentioned, not sure if this is on purpose, or an issue. 
Cheers

**Comment by adametry** [comment]
It is my understanding that the `checkstyle` formatter is intended to match the [jshint reporter](http://jshint.com/docs/cli/). 

Just the same, the formatter isn't a part of the `gulp-eslint` project, which supports using `eslint` (and its formatters) in a `gulp` virtual file stream. For a solid answer/resolution, submit an issue with the [eslint](https://github.com/eslint/eslint) project.

**Comment by mhartington** [comment]
Ahh alright, thanks for the heads up!
