### ISSUE TITLE
Make eslint a peer dependency

### ISSUE THREAD

**Issue by davidmason** [adametry/gulp-eslint#68]
If an eslint plugin specifies eslint as a peer dependency, npm can check that a compatible version of eslint is installed, but the extra copy of eslint installed under gulp-eslint is hidden from this check, so there is risk of plugins being run with an incompatible eslint version.

If both gulp-eslint and the plugins specify eslint as a peer dependency, both will use the same version, and npm will flag incompatibilities during install.

Implemented in https://github.com/adametry/gulp-eslint/pull/67

**Comment by shinnn** [comment]
We won't. Read the previous discussion. https://github.com/adametry/gulp-eslint/pull/19#issuecomment-71404986

**Comment by davidmason** [comment]
@shinnn cool, thanks for the prompt response.

Looks like the general pattern of *thing-with-plugins*, *plugin-for-thing* and *runner-integration-for-thing* and ensuring compatible versions is a bit of an unsolved issue in npm at the moment.

I don't think I even have enough weekend left to read through https://github.com/npm/npm/issues/5080 so for now it seems a lot easier to just put up with having 2 identical copies of eslint in my node_modules.

**Comment by shinnn** [comment]
> the extra copy of eslint installed under gulp-eslint is hidden from this check, so there is risk of plugins being run with an incompatible eslint version.

Use npm >= 3 and you won't run into this problem any more.
