### ISSUE TITLE
root .eslintignore is suspended when subfolder contains .eslintignore file

### ISSUE THREAD

**Issue by weitenghuang** [adametry/gulp-eslint#69]
Even root directory's .eslintignore has `node_modules/**`, gulp-eslint still lint .js files under node_modules folder if the subfolder has .eslintignore file
https://github.com/adametry/gulp-eslint/issues/11

**Comment by axelg12** [comment]
+1

**Comment by axelg12** [comment]
I can ignore this by adding **/node_modules/** but that creates warnings that I don't like

**Comment by weitenghuang** [comment]
I basically ignore it from `gulp.src`. But it will be nice if i can just use `.eslintignore` file
```
gulp.src(['./**/*.js','./**/*.jsx','!./node_modules/**']) 
```

**Comment by adametry** [comment]
Like eslint, gulp-eslint only loads a single .eslintignore file; though, gulp-eslint will search for .eslintignore relative to the file path rather than cwd. This ends up being a more flexible approach, allowing localized .eslintignore, and cwd-based exclusions (as demonstrated with gulp.src).

**Comment by onlywei** [comment]
Ah, I see. This makes it so that I basically don't ever use the `.eslintignore` and rely completely on `gulp.src()` to lint my files.
