### ISSUE TITLE
Problem with eslintrc: "indent" is invalid: Value "4" must be an enum value

### ISSUE THREAD

**Issue by tschoartschi** [adametry/gulp-eslint#72]
I use gulp-eslint as follows:

```javascript
var standaloneScript = 'public/api/config-api.js';
gulp.task('eslint', function () {
    return gulp.src(standaloneScript)
        .pipe($.eslint())
        .pipe($.eslint.format())
        .pipe($.eslint.failOnError());
});
```

In my root folder I have a eslintrc specified. But eslint crashes because of the indent rule. It says:

        Configuration for rule "indent" is invalid:
        Value "4" must be an enum value.

```javascript
//...
"rules": {
        "indent": [4, 4],
//...
```
What can I do? Removing indent works, but this is not an option for me. Could you help me to resolve this issue?

**Comment by shinnn** [comment]
Great, the error message exactly tells us what you should do. I love such a good design of ESLint.

That's an issue with your .eslintrc. Read the ESLint documentation carefully.

* http://eslint.org/docs/user-guide/configuring#configuring-rules
* http://eslint.org/docs/rules/indent

**Comment by tschoartschi** [comment]
@shinnn thanks for the hint. Now it works. If someone has the same problem, defining the indent rule as
```javascript
{
//...
"indent": [2, 4]
//...
}
````
worked for me. Why I didn't thought it is a problem with the rule is, that I used this exact .eslintrc with ember-cli-eslint also and there I had never any problems.

**Comment by shinnn** [comment]
I found the cause. [ember-cli-eslint](https://github.com/jonathanKingston/ember-cli-eslint) [uses](https://github.com/jonathanKingston/ember-cli-eslint/blob/c504f6b1ecca86fd70c1fe18b835cc59456c8d32/package.json#L58) [broccoli-lint-eslint](https://github.com/jonathanKingston/broccoli-lint-eslint), that still uses [eslint v0.22.x](https://github.com/jonathanKingston/broccoli-lint-eslint/blob/729db004c5351a8a147223be5e256b54e18a9d6c/package.json#L32). And, the config validation feature is only available from eslint v0.23.0 or newer. http://eslint.org/blog/2015/06/eslint-0.23.0-released/#configuration-validation

**Comment by tschoartschi** [comment]
@shinnn very interesting! Thanks a lot for the detailed information :+1:

**Comment by jonathanKingston** [comment]
@shinnn please in future let me know or better yet submit a patch. Things have been busy in the last two months however I hope to get stuff patched soon to be v1 safe.

**Comment by shinnn** [comment]
@jonathanKingston I won't, because I'm currently not an actual user of ember-cli-eslint. I just needed to look into your code to answer the question reported here.
