### ISSUE TITLE
Save output of eslint.format() in a file

### ISSUE THREAD

**Issue by 4kochi** [adametry/gulp-eslint#74]
I am new to gulp, so sorry in advance for this maybe silly question. 

I will generate a checkstyle report of eslint a save it in a xml file. But i am not sure how the output option in format() works. Here is my example:

```
gulp.task('checkstyle', function () {
        gulp.src(src)
            .pipe(eslint())
            .pipe(eslint.format('checkstyle', require('fs').createWriteStream('.reports/eslint_checkstyle.xml')))
            .pipe(eslint.failAfterError());
    });
```

This works fine as long as the .reports folder exist. Otherwise i get an error that the directory not exists. But i did not found a gulp plugin which can create a directory. I know that `gulp.dest()` creates directories automatically. But i don't know if i can use `gulp.dest()` in this scenario.

So should i use plain node.js to create the directory before the task runs? Or is there a more elegant solution using gulp?

Thanks.

**Comment by shinnn** [comment]
> should i use plain node.js to create the directory before the task runs?

In this case, yes.
