### ISSUE TITLE
failOnError() throws "Unhandled 'error' event"

### ISSUE THREAD

**Issue by 4kochi** [adametry/gulp-eslint#75]
If have the following task:

```
gulp.task('lint', function () {
        gulp.src(src)
            .pipe(eslint())
            .pipe(eslint.formatEach())
            .pipe(eslint.failOnError());
    });
```

If stops after the first error and prints the error message. But i also get an error from events.js.

![bildschirmfoto 2015-07-15 um 08 37 35](https://cloud.githubusercontent.com/assets/1742426/8692283/28ce3c20-2acd-11e5-9b20-8520f49bb63a.png)

I am using io.js 2.3.4 and gulp 3.9.0

**Comment by shinnn** [comment]
That is just what [`failOnError`](https://github.com/adametry/gulp-eslint/tree/0dd1ae57b666747246d3e679bdd017ea43c20fb7#eslintfailaftererror) does.
