### ISSUE TITLE
space-infix-ops and brackets in ternaries

### ISSUE THREAD

**Issue by alexfedoseev** [adametry/gulp-eslint#76]
gulp-eslint falls on cases when brackets are used in ternaries (with cli it's ok).

```js
const val = smth ? (smth + 1) : 0;
```

```
error  Infix operators must be spaced  space-infix-ops
```

**Comment by shinnn** [comment]
> with cli it's ok

No.

```
$ eslint --version
v0.24.0
$ echo "const val = smth ? (smth + 1) : 0;" | eslint --stdin

<text>
  1:1  error  Unexpected token const

✖ 1 problem (1 error, 0 warnings)
```

Seems an issue with your environment and setting.

**Comment by alexfedoseev** [comment]
Enable `blockBindings` and check again.

```json
"ecmaFeatures": {
  "blockBindings": true
}
```

**Comment by shinnn** [comment]
```
$ eslint --version
v0.24.0
$ printf "ecmaFeatures:\n  blockBindings: true\n" > .eslintrc
$ echo "const val = smth ? (smth + 1) : 0;" | eslint --stdin

<text>
  1:6   error  val is defined but never used  no-unused-vars
  1:12  error  "smth" is not defined          no-undef
  1:20  error  "smth" is not defined          no-undef
```

**Comment by alexfedoseev** [comment]
So there is no `error  Infix operators must be spaced  space-infix-ops`.
But with gulp-eslint there is. Using latest version from npm.

**Comment by shinnn** [comment]
```js
'use strict';

var gulpEslint = require('gulp-eslint');
var gulp = require('gulp');

gulp.task('default', function() {
  return gulp.src('fixture.js')
    .pipe(gulpEslint())
    .pipe(gulpEslint.format())
    .pipe(gulpEslint.failOnError());
});
```

```
$ npm install gulp@3.9.0 gulp-eslint@0.15.0
$ echo "const val = smth ? (smth + 1) : 0;" > fixture.js
$ node node_modules/.bin/gulp
[20:55:38] Using gulpfile ~/repos/gulp-eslint-issue76/gulpfile.js
[20:55:38] Starting 'default'...
[20:55:38] 'default' errored after 46 ms
[20:55:38] ESLintError in plugin 'gulp-eslint'
Message:
    Unexpected token const
Details:
    fileName: /Users/shinnn/repos/gulp-eslint-issue76/fixture.js
    lineNumber: 1
[20:55:38] 
/Users/shinnn/repos/gulp-eslint-issue76/fixture.js
  1:1  error  Unexpected token const

✖ 1 problem (1 error, 0 warnings)
```

**Comment by alexfedoseev** [comment]
Well here is my case:

![screen shot 2015-07-20 at 15 17 51](https://cloud.githubusercontent.com/assets/4244251/8775613/96ba6c26-2ef2-11e5-9c7e-6edefb667c30.png)


[gulpfile.js](https://github.com/alexfedoseev/generator-flux-on-rails/blob/master/app/templates/app/gulpfile.babel.js#L156) | [.eslintrc](https://github.com/alexfedoseev/generator-flux-on-rails/blob/master/app/templates/app/.eslintrc)

**tmp.js**

```js
export default (smth) => {
  const val = smth ? (smth + 1) : 0;
  return val;
}
```

Can you check with my `.eslintrc`?

**Comment by shinnn** [comment]
```
$ curl -s https://raw.githubusercontent.com/alexfedoseev/generator-flux-on-rails/8f826bc56ec8ceafe86ae6740198ebae086ccdaf/app/templates/app/.eslintrc > .eslintrc
$ eslint --version
v0.24.0
$ npm install babel-eslint
$ echo "const val = smth ? (smth + 1) : 0;" | eslint --stdin

<text>
  1:12  error    "smth" used outside of binding context  block-scoped-var
  1:12  error    "smth" is not defined                   no-undef
  1:20  error    "smth" used outside of binding context  block-scoped-var
  1:20  error    "smth" is not defined                   no-undef
  1:30  warning  Infix operators must be spaced          space-infix-ops

✖ 5 problems (4 errors, 1 warning)
```

>  warning  Infix operators must be spaced          space-infix-ops

**Comment by alexfedoseev** [comment]
It's `"parser": "babel-eslint"`.

Eslint cli is ok with it, gulp-eslint falls on subject case.

**Comment by shinnn** [comment]
> It's `"parser": "babel-eslint"`.

Yes, this case https://github.com/adametry/gulp-eslint/issues/76#issuecomment-122869021 uses babel-eslint via .eslintrc. https://github.com/alexfedoseev/generator-flux-on-rails/blob/8f826bc56ec8ceafe86ae6740198ebae086ccdaf/app/templates/app/.eslintrc#L41 And as you can see, it shows an error message `warning  Infix operators must be spaced  space-infix-ops`.

> Eslint cli is ok with it,

Oh, interesting. Is this output is *OK* for you?

```
tmp.js
  2:32  warning  Infix operators must be spaced  space-infix-ops

✖ 1 problem (0 errors, 1 warning)
```

**Comment by shinnn** [comment]
I strongly recommend you to read this article before opening new issues on Open Source projects. http://www.catb.org/esr/faqs/smart-questions.html

**Comment by alexfedoseev** [comment]
> Oh, interesting. Is this output is OK for you?

![screen shot 2015-07-20 at 16 15 40](https://cloud.githubusercontent.com/assets/4244251/8776554/c4bbdf6c-2efa-11e5-9f42-66241c4bacab.png)

In my case eslint cli doesn't show any errors.

**Comment by shinnn** [comment]
@alexfedoseev Can you create a small repository that can reproduce the problem you're running into?

**Comment by alexfedoseev** [comment]
Yep, here it is: https://github.com/alexfedoseev/eslint-issue

![screen shot 2015-07-20 at 16 46 41](https://cloud.githubusercontent.com/assets/4244251/8777248/92510354-2eff-11e5-99ef-7d744329abd1.png)

**Comment by shinnn** [comment]
@alexfedoseev Can you show me the result this command in [your repository](https://github.com/alexfedoseev/eslint-issue)'s root directory:

```
node node_modules/gulp-eslint/node_modules/.bin/eslint code.js
```

**Comment by alexfedoseev** [comment]
```
$ npm --version
2.9.1

$ node --version
v0.12.2

$ which eslint
/usr/local/bin/eslint

$ node node_modules/gulp-eslint/node_modules/.bin/eslint code.js

code.js
  2:32  warning  Infix operators must be spaced  space-infix-ops

✖ 1 problem (0 errors, 1 warning)

```

**Comment by shinnn** [comment]
> ```
> $ node node_modules/gulp-eslint/node_modules/.bin/eslint code.js
> 
> code.js
>   2:32  warning  Infix operators must be spaced  space-infix-ops
> 
> ✖ 1 problem (0 errors, 1 warning)
> ```

OK cleanly installed eslint CLI works well too in your environment. So, I confidently say [this](https://github.com/adametry/gulp-eslint/issues/76#issuecomment-122852822) again:

> Seems an issue with your environment and setting.

At least it's not related to this repository [gulp-eslint](https://github.com/adametry/gulp-eslint). if the problem still occurs even after you reinstall the your `eslint` command, please open the issue in a proper issue tracker (probably, https://github.com/eslint/eslint/issues).

**Comment by alexfedoseev** [comment]
I've already reinstalled eslint globally, but problem still occurs. Anyway, thanks!
