### ISSUE TITLE
options.envs should be options.env

### ISSUE THREAD

**Issue by kblcuk** [adametry/gulp-eslint#77]
According to [eslint docs](http://eslint.org/docs/user-guide/configuring) environments are defined in `env`, your documentations says `envs`.

**Comment by shinnn** [comment]
It follows the ESLint API. http://eslint.org/docs/developer-guide/nodejs-api#cliengine

And `env` is supported (but deprecated) too.

**Comment by kblcuk** [comment]
Well, with current version of gulp-eslint, setting `envs` does nothing.

**Comment by kblcuk** [comment]
Well, with current version of gulp-eslint, setting `envs` does nothing.
