### ISSUE TITLE
eslint dependency update

### ISSUE THREAD

**Issue by zdychacek** [adametry/gulp-eslint#78]
Hi,

could I ask you when will be `eslint` dependecy updated to the newest version (v1.0.0-rc-3)?

I'd like to use new `arrow-parens` rule.

Thx for your reply.

O.

**Comment by adametry** [comment]
I'm working on an update to match the 1.0.0(-rc-*) changes. I'll have an update out this week (likely as a matching -rc version until eslint 1.0.0 is live).

**Comment by zdychacek** [comment]
Thanks for you reply :+1:
