### ISSUE TITLE
YAML error

### ISSUE THREAD

**Issue by TrySound** [adametry/gulp-eslint#81]
Need to catch yaml error or any other error and convert to PluginError. Just for more clean error reporting.

**Comment by shinnn** [comment]
> Need to catch yaml error or any other error

I don't know what you mean by "any other error", but at least throwing an error when the plugin received an invalid config file is a proper behavior. According to [the plugin guideline](https://github.com/gulpjs/gulp/blob/f58b17cefa00245eb6d849bfe901174f89c89620/docs/writing-a-plugin/guidelines.md):

> If you encounter an error **outside** the stream, such as invalid configuration while creating the stream, you may throw it.

**Comment by TrySound** [comment]
I meant something like this [here](https://github.com/adametry/gulp-eslint/blob/master/index.js#L19-L21)
```js
try {
  return linter.executeOnText(str, filePath).results[0];
} catch(e) {
  options.done(new PluginError('gulp-eslint', e))
}
```
With this in my task I can
```js
gulp.src(...)
  .pipe(eslint())
  .on('error', done)
```

**Comment by shinnn** [comment]
I understood and now I'm sure it's not needed. In this case just throwing a YAML syntax error better matches "the gulp way".

Please read [*Why are these guidelines so strict?*](https://github.com/gulpjs/gulp/blob/f58b17cefa00245eb6d849bfe901174f89c89620/docs/writing-a-plugin/guidelines.md#why-are-these-guidelines-so-strict) section in the guideline. I totally agree on it.

Thanks.
