### ISSUE TITLE
Linting not happening (Windows 7)

### ISSUE THREAD

**Issue by PanzerKunst** [adametry/gulp-eslint#87]
Hi,

I can't get gulp-eslint to lint. I have created a project with the minimum files, the task is launched, but no error is displayed although the unique file to lint has errors.

Project files:
- package.json
- gulpfile.js
- scripts/index.js

package.json:

    {
      "name": "gulp-eslint-test",
      "version": "1.0.0",
      "description": "",
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "gulp": "^3.9.0",
        "gulp-eslint": "^1.0.0"
      }
    }

gulpfile.js:

    var gulp = require('gulp'),
        eslint = require('gulp-eslint');

    gulp.task('lint', function () {
        return gulp.src('scripts/index.js')
            // eslint() attaches the lint output to the eslint property
            // of the file object so it can be used by other modules.
            .pipe(eslint())
            // eslint.format() outputs the lint results to the console.
            // Alternatively use eslint.formatEach() (see Docs).
            .pipe(eslint.format())
            // To have the process exit with an error code (1) on
            // lint error, return the stream and pipe to failOnError last.
            .pipe(eslint.failOnError());
    });

    gulp.task('default', ['lint'], function () {
        // This will only run if the lint task is successful...
    });

scripts/index.js:

    CR.Index = {};

Result of `gulp` command:

    [11:34:33] Using gulpfile c:\Temp\gulp-eslint-test\gulpfile.js
    [11:34:33] Starting 'lint'...
    [11:34:33] Finished 'lint' after 52 ms
    [11:34:33] Starting 'default'...
    [11:34:33] Finished 'default' after 7.5 μs

The lint should fail, indicating that `CR` is undefined in `index.js`.

I'm using Windows 7.

Any clue where the issue is?

**Comment by shinnn** [comment]
How does your `.eslintrc` look like?

**Comment by adametry** [comment]
As of eslint 1.0.0, all rules are [off by default](http://eslint.org/docs/user-guide/migrating-to-1.0.0#all-rules-off-by-default). Your project should either include an `.eslintrc` file or be configured via `gulp-eslint`. If you believe you are already configuring eslint, be sure that the `no-undef` rule is declared as an error (2); otherwise, it will be ignored by `failOnError`.

**Comment by PanzerKunst** [comment]
> As of eslint 1.0.0, all rules are off by default

Problem solved, thanks!
