### ISSUE TITLE
eslint takes anywhere from 2 to 40 seconds to run.

### ISSUE THREAD

**Issue by seiyria** [adametry/gulp-eslint#89]
I have no idea why. You can see my [gulpfile here](https://github.com/seiyria/Roguathia/blob/master/gulpfile.js).

**Comment by seiyria** [comment]
Using `gulp-changed` I was able to bring this back down into a reasonable period of time.

**Comment by seiyria** [comment]
Just kidding, this still happens, though much less frequently.

**Comment by adametry** [comment]
Does gulp take 2-40s to report `Starting 'eslint'...` or does it report `Finished 'eslint' after [2-40] s`? 

Depending on where the delay is, you might do one/both of the following:
* **For slow to start:** Cut down on unnecessary module loading by requiring needed modules *within* the individual tasks.
* **For slow to finish:** Make sure you're not linting unexpected files by (temporarily) including `gulp-debug` in the lint stream (ideally before `failOnError`). I get a fairly consistent 3.4s (±0.2s) task time when running `gulp eslint` (not bad for 85 files). Also, keep an eye on your system memory. If your machine starts paging memory, you can see a big decrease in performance. 

If the above suggestions don't help, try running eslint directly from the command line to determine if the issue can be isolated to `gulp-eslint` or `eslint`.

**Comment by seiyria** [comment]
For me it's slow to finish. I'm not using gulp-debug anywhere, I think. I just have debug for browserify. I hadn't really considered memory though. I gave my VM about 5 GB of RAM and 2 processor cores so I didn't expect many issues with it. However, I don't seem to notice it when I just do `gulp eslint` - it's only when it's a part of the browserify chain. I'll be honest: I have no idea how it works, I didn't write the browserify segment, so it might be running horribly inefficiently.

**Comment by seiyria** [comment]
Yeah, this is probably definitely me. I just started watching RAM and CPU and my RAM usage skyrockets. I'll probably solve this the lame way and just give myself more RAM.

Thanks for pointing me in that direction!
