### ISSUE TITLE
failAfterError() doesn't cause Gulp to exit with non-zero exit status

### ISSUE THREAD

**Issue by atesgoral** [adametry/gulp-eslint#93]
`failOnError()` does cause Gulp to exit with a non-zero exit status while `failAfterError()` doesn't.

**Comment by adametry** [comment]
Can you provide an example?

**Comment by atesgoral** [comment]
Real example:

```
gulp.task('lint-js', function () {
    gulp.src([ 'src/**/*.js', 'test/intern/**/*.js' ])
        .pipe(eslint())
        .pipe(eslint.formatEach())
        .pipe(eslint.failAfterError());
});
```

`gulp lint-js` shell exit code is 0. When I use `failOnError()` instead, the exit code is 1.

**Comment by atesgoral** [comment]
Perhaps the `cb()` call at [https://github.com/adametry/gulp-eslint/blob/master/index.js#L101](line 101 of index.js) need to be passed an error?

**Comment by adametry** [comment]
Be sure to return the stream in the gulp task.

**Comment by atesgoral** [comment]
D'oh! Thanks, that fixed it.
